//-----------------------------------------------------------------------------
// This code was generated by a tool.
// Changes to this file will be lost if the code is regenerated.
//-----------------------------------------------------------------------------
using System;
using Tp.Integration.Common;

namespace Tp.Integration.Common
{
    /// <summary>
    /// Data Transfer object of Custom Report. Represents Custom Report.
	/// TargetProcess system usage only
    /// </summary>
	[Serializable]
	public partial class CustomReportDTO : DataTransferObject
	{
        /// <summary>
        /// Gets or sets the ID.
        /// </summary>
        /// <value>The ID.</value>		
		[PrimaryKey]
		public override int? ID
		{
			get { return CustomReportID; }
			set
			{
				if (value == int.MinValue)
					value = null;

				CustomReportID = value;
			}
		}

        /// <summary>
        /// Gets or sets the Custom Report ID.
        /// </summary>
        /// <value>The Custom Report ID.</value>
		[PrimaryKey]
		public int? CustomReportID { get; set; }
		

		/// <summary>
        /// Gets or sets the Name. Name
        /// </summary>
        /// <value>The Name.</value>
		public String Name { get; set; }

		/// <summary>
        /// Gets or sets the Reporting Entity Name. Reporting Entity Name
        /// </summary>
        /// <value>The Reporting Entity Name.</value>
		public String ReportingEntityName { get; set; }

		/// <summary>
        /// Gets or sets the Is Public. Is Public
        /// </summary>
        /// <value>The Is Public.</value>
		public Boolean? IsPublic { get; set; }

		/// <summary>
        /// Gets or sets the Content. Content
        /// </summary>
        /// <value>The Content.</value>
		public String Content { get; set; }
		
		/// <summary>
        /// Gets or sets the Process ID. 
        /// </summary>
        /// <value>The Process ID.</value>
		[ForeignKey]
		public Int32? ProcessID { get; set; }
		
		/// <summary>
        /// Gets or sets the Owner ID. Owner
        /// </summary>
        /// <value>The Owner ID.</value>
		[ForeignKey]
		public Int32? OwnerID { get; set; }
		

		
		/// <summary>
        /// Gets or sets the Process Name. 
        /// </summary>
        /// <value>The Process Name.</value>
		[RelationName]
		public virtual string ProcessName { get; set; }
		
	}
	
	
	/// <summary>
    /// Custom Report fields
    /// </summary>
	public enum CustomReportField
	{
        /// <summary>
        /// Name
        /// </summary>		
		Name,
        /// <summary>
        /// Reporting Entity Name
        /// </summary>		
		ReportingEntityName,
        /// <summary>
        /// Is Public
        /// </summary>		
		IsPublic,
        /// <summary>
        /// Content
        /// </summary>		
		Content,
        /// <summary>
        /// Process ID
        /// </summary>		
		ProcessID,
        /// <summary>
        /// Owner ID
        /// </summary>		
		OwnerID,
        /// <summary>
        /// Process Name
        /// </summary>		
		ProcessName,
	}
}