//-----------------------------------------------------------------------------
// This code was generated by a tool.
// Changes to this file will be lost if the code is regenerated.
//-----------------------------------------------------------------------------
using System;
using Tp.Integration.Common;

namespace Tp.Integration.Common
{
    /// <summary>
    /// Data Transfer object of External Reference. 
    /// </summary>
	[Serializable]
	public partial class ExternalReferenceDTO : DataTransferObject
	{
        /// <summary>
        /// Gets or sets the ID.
        /// </summary>
        /// <value>The ID.</value>		
		[PrimaryKey]
		public override int? ID
		{
			get { return ExternalReferenceID; }
			set
			{
				if (value == int.MinValue)
					value = null;

				ExternalReferenceID = value;
			}
		}

        /// <summary>
        /// Gets or sets the External Reference ID.
        /// </summary>
        /// <value>The External Reference ID.</value>
		[PrimaryKey]
		public int? ExternalReferenceID { get; set; }
		

		/// <summary>
        /// Gets or sets the Tp ID. 
        /// </summary>
        /// <value>The Tp ID.</value>
		public Int32? TpID { get; set; }

		/// <summary>
        /// Gets or sets the External ID. 
        /// </summary>
        /// <value>The External ID.</value>
		public String ExternalID { get; set; }

		/// <summary>
        /// Gets or sets the Create Date. 
        /// </summary>
        /// <value>The Create Date.</value>
		public DateTime? CreateDate { get; set; }
		
		/// <summary>
        /// Gets or sets the Plugin Profile ID. 
        /// </summary>
        /// <value>The Plugin Profile ID.</value>
		[ForeignKey]
		public Int32? PluginProfileID { get; set; }
		

		
		/// <summary>
        /// Gets or sets the Entity Type Name. 
        /// </summary>
        /// <value>The Entity Type Name.</value>
		[RelationName]
		public virtual string EntityTypeName { get; set; }
		
	}
	
	
	/// <summary>
    /// External Reference fields
    /// </summary>
	public enum ExternalReferenceField
	{
        /// <summary>
        /// Tp ID
        /// </summary>		
		TpID,
        /// <summary>
        /// External ID
        /// </summary>		
		ExternalID,
        /// <summary>
        /// Create Date
        /// </summary>		
		CreateDate,
        /// <summary>
        /// Plugin Profile ID
        /// </summary>		
		PluginProfileID,
        /// <summary>
        /// Entity Type Name
        /// </summary>		
		EntityTypeName,
	}
}