//-----------------------------------------------------------------------------
// This code was generated by a tool.
// Changes to this file will be lost if the code is regenerated.
//-----------------------------------------------------------------------------
using System;
using Tp.Integration.Common;

namespace Tp.Integration.Common
{
    /// <summary>
    /// Data Transfer object of General Numeric Priority List Item. 
	/// TargetProcess system usage only
    /// </summary>
	[Serializable]
	public partial class GeneralNumericPriorityListItemDTO : DataTransferObject
	{
        /// <summary>
        /// Gets or sets the ID.
        /// </summary>
        /// <value>The ID.</value>		
		[PrimaryKey]
		public override int? ID
		{
			get { return GeneralID; }
			set
			{
				if (value == int.MinValue)
					value = null;

				GeneralID = value;
			}
		}

        /// <summary>
        /// Gets or sets the General ID.
        /// </summary>
        /// <value>The General ID.</value>
		[PrimaryKey]
		public int? GeneralID { get; set; }
		

		/// <summary>
        /// Gets or sets the Parent Project ID. 
        /// </summary>
        /// <value>The Parent Project ID.</value>
		public Int32? ParentProjectID { get; set; }

		/// <summary>
        /// Gets or sets the Numeric Priority. 
        /// </summary>
        /// <value>The Numeric Priority.</value>
		public Double? NumericPriority { get; set; }

		/// <summary>
        /// Gets or sets the Entity Type ID. 
        /// </summary>
        /// <value>The Entity Type ID.</value>
		public Int32? EntityTypeID { get; set; }
		

		
	}
	
	
	/// <summary>
    /// General Numeric Priority List Item fields
    /// </summary>
	public enum GeneralNumericPriorityListItemField
	{
        /// <summary>
        /// Parent Project ID
        /// </summary>		
		ParentProjectID,
        /// <summary>
        /// Numeric Priority
        /// </summary>		
		NumericPriority,
        /// <summary>
        /// Entity Type ID
        /// </summary>		
		EntityTypeID,
	}
}