//-----------------------------------------------------------------------------
// This code was generated by a tool.
// Changes to this file will be lost if the code is regenerated.
//-----------------------------------------------------------------------------
using System;
using Tp.Integration.Common;

namespace Tp.Integration.Common
{
    /// <summary>
    /// Data Transfer object of Message General. Relation between message and general.
	/// TargetProcess system usage only
    /// </summary>
	[Serializable]
	public partial class MessageGeneralDTO : DataTransferObject
	{
        /// <summary>
        /// Gets or sets the ID.
        /// </summary>
        /// <value>The ID.</value>		
		[PrimaryKey]
		public override int? ID
		{
			get { return MessageGeneralID; }
			set
			{
				if (value == int.MinValue)
					value = null;

				MessageGeneralID = value;
			}
		}

        /// <summary>
        /// Gets or sets the Message General ID.
        /// </summary>
        /// <value>The Message General ID.</value>
		[PrimaryKey]
		public int? MessageGeneralID { get; set; }
		
		
		/// <summary>
        /// Gets or sets the Message ID. Reference to message
        /// </summary>
        /// <value>The Message ID.</value>
		[ForeignKey]
		public Int32? MessageID { get; set; }
		
		/// <summary>
        /// Gets or sets the General ID. Reference to general
        /// </summary>
        /// <value>The General ID.</value>
		[ForeignKey]
		public Int32? GeneralID { get; set; }
		

		
		/// <summary>
        /// Gets or sets the General Name. Reference to general
        /// </summary>
        /// <value>The General Name.</value>
		[RelationName]
		public virtual string GeneralName { get; set; }
		
	}
	
	
	/// <summary>
    /// Message General fields
    /// </summary>
	public enum MessageGeneralField
	{
        /// <summary>
        /// Message ID
        /// </summary>		
		MessageID,
        /// <summary>
        /// General ID
        /// </summary>		
		GeneralID,
        /// <summary>
        /// General Name
        /// </summary>		
		GeneralName,
	}
}