//-----------------------------------------------------------------------------
// This code was generated by a tool.
// Changes to this file will be lost if the code is regenerated.
//-----------------------------------------------------------------------------
using System;
using System.Xml.Serialization;
using Tp.Integration.Common;

namespace Tp.Integration.Common
{
    /// <summary>
    /// Data Transfer object of Project Member. Represents Project Member. Project member is a part of project team and has access to the project.
    /// </summary>
	[Serializable]
	public partial class ProjectMemberDTO : DataTransferObject
	{
        /// <summary>
        /// Gets or sets the ID.
        /// </summary>
        /// <value>The ID.</value>		
		[PrimaryKey]
		public override int? ID
		{
			get { return ProjectMemberID; }
			set
			{
				if (value == int.MinValue)
					value = null;

				ProjectMemberID = value;
			}
		}

        /// <summary>
        /// Gets or sets the Project Member ID.
        /// </summary>
        /// <value>The Project Member ID.</value>
		[PrimaryKey]
		[XmlElement(Order = 3)]public int? ProjectMemberID { get; set; }
		

		/// <summary>
        /// Gets or sets the Weekly Available Hours. Indicates how much time the person can spend on project per week
        /// </summary>
        /// <value>The Weekly Available Hours.</value>
		[XmlElement(Order = 4)]public Decimal? WeeklyAvailableHours { get; set; }


		/// <summary>
        /// Gets or sets the Membership End Date. The date when the person is leaving the team
        /// </summary>
        /// <value>The Membership End Date.</value>
		[XmlElement(Order = 5)]public DateTime? MembershipEndDate { get; set; }

		/// <summary>
        /// Gets or sets the Allocation. Indicates how much in % user works for the project
        /// </summary>
        /// <value>The Allocation.</value>
		[XmlElement(Order = 6)]public Int32? Allocation { get; set; }
		
		/// <summary>
        /// Gets or sets the Project ID. Reference to project
        /// </summary>
        /// <value>The Project ID.</value>
		[ForeignKey]
		[XmlElement(Order = 7)]public Int32? ProjectID { get; set; }
		
		/// <summary>
        /// Gets or sets the User ID. Reference to person
        /// </summary>
        /// <value>The User ID.</value>
		[ForeignKey]
		[XmlElement(Order = 8)]public Int32? UserID { get; set; }
		
		/// <summary>
        /// Gets or sets the Role ID. Person role in the project. For example, Developer or Project Manager
        /// </summary>
        /// <value>The Role ID.</value>
		[ForeignKey]
		[XmlElement(Order = 9)]public Int32? RoleID { get; set; }
		

		
		/// <summary>
        /// Gets or sets the Project Name. Reference to project
        /// </summary>
        /// <value>The Project Name.</value>
		[RelationName]
		[XmlElement(Order = 10)]public virtual string ProjectName { get; set; }
		
		/// <summary>
        /// Gets or sets the Role Name. Person role in the project. For example, Developer or Project Manager
        /// </summary>
        /// <value>The Role Name.</value>
		[RelationName]
		[XmlElement(Order = 11)]public virtual string RoleName { get; set; }

		/// <summary>
		/// Gets or sets the Membership Start Date. The date when the person joins the team
		/// </summary>
		/// <value>The Membership Start Date.</value>
		[XmlElement(Order = 12)]
		public DateTime? MembershipStartDate { get; set; }
	}
	
	
	/// <summary>
    /// Project Member fields
    /// </summary>
	public enum ProjectMemberField
	{
        /// <summary>
        /// Weekly Available Hours
        /// </summary>		
		WeeklyAvailableHours,
        /// <summary>
        /// Membership Start Date
        /// </summary>		
		MembershipStartDate,
        /// <summary>
        /// Membership End Date
        /// </summary>		
		MembershipEndDate,
        /// <summary>
        /// Allocation
        /// </summary>		
		Allocation,
        /// <summary>
        /// Project ID
        /// </summary>		
		ProjectID,
        /// <summary>
        /// User ID
        /// </summary>		
		UserID,
        /// <summary>
        /// Role ID
        /// </summary>		
		RoleID,
        /// <summary>
        /// Project Name
        /// </summary>		
		ProjectName,
        /// <summary>
        /// Role Name
        /// </summary>		
		RoleName,
	}
}
