//-----------------------------------------------------------------------------
// This code was generated by a tool.
// Changes to this file will be lost if the code is regenerated.
//-----------------------------------------------------------------------------
using System;
using Tp.Integration.Common;

namespace Tp.Integration.Common
{
    /// <summary>
    /// Data Transfer object of Project. Represents Project. Project is a core entity which contains releases, feature, user stories, bugs, etc..
    /// </summary>
	[Serializable]
	public partial class ProjectDTO : DataTransferObject
	{
        /// <summary>
        /// Gets or sets the ID.
        /// </summary>
        /// <value>The ID.</value>		
		[PrimaryKey]
		public override int? ID
		{
			get { return ProjectID; }
			set
			{
				if (value == int.MinValue)
					value = null;

				ProjectID = value;
			}
		}

        /// <summary>
        /// Gets or sets the Project ID.
        /// </summary>
        /// <value>The Project ID.</value>
		[PrimaryKey]
		public int? ProjectID { get; set; }
		

		/// <summary>
        /// Gets or sets the Name. Entity name or title
        /// </summary>
        /// <value>The Name.</value>
		public String Name { get; set; }

		/// <summary>
        /// Gets or sets the Description. Entity description
        /// </summary>
        /// <value>The Description.</value>
		public String Description { get; set; }

		/// <summary>
		/// Gets or sets the Abbreviation. Project abbreviation
        /// </summary>
		/// <value>The Abbreviation.</value>
		public String Abbreviation { get; set; }
		
		/// <summary>
        /// Gets or sets the Start Date. For example, start date of the iteration. Relevant for Iteration, Project, Release.
        /// </summary>
        /// <value>The Start Date.</value>
		public DateTime? StartDate { get; set; }

		/// <summary>
        /// Gets or sets the End Date. For example, end date of the iteration. Relevant for Iteration, Project, Release.
        /// </summary>
        /// <value>The End Date.</value>
		public DateTime? EndDate { get; set; }

		/// <summary>
        /// Gets or sets the Create Date. Date when entity has been created
        /// </summary>
        /// <value>The Create Date.</value>
		public DateTime? CreateDate { get; set; }

		/// <summary>
        /// Gets or sets the Modify Date. Date when entity has been modified
        /// </summary>
        /// <value>The Modify Date.</value>
		public DateTime? ModifyDate { get; set; }

		/// <summary>
        /// Gets or sets the Last Comment Date. Last comment date
        /// </summary>
        /// <value>The Last Comment Date.</value>
		public DateTime? LastCommentDate { get; set; }

		/// <summary>
        /// Gets or sets the Numeric Priority. Calculated priority of entity. Valid for UserStory and Bug for now
        /// </summary>
        /// <value>The Numeric Priority.</value>
		public Double? NumericPriority { get; set; }

		/// <summary>
        /// Gets or sets the Custom Field1. Reserved property for custom field
        /// </summary>
        /// <value>The Custom Field1.</value>
		public String CustomField1 { get; set; }

		/// <summary>
        /// Gets or sets the Custom Field2. Reserved property for custom field
        /// </summary>
        /// <value>The Custom Field2.</value>
		public String CustomField2 { get; set; }

		/// <summary>
        /// Gets or sets the Custom Field3. Reserved property for custom field
        /// </summary>
        /// <value>The Custom Field3.</value>
		public String CustomField3 { get; set; }

		/// <summary>
        /// Gets or sets the Custom Field4. Reserved property for custom field
        /// </summary>
        /// <value>The Custom Field4.</value>
		public String CustomField4 { get; set; }

		/// <summary>
        /// Gets or sets the Custom Field5. Reserved property for custom field
        /// </summary>
        /// <value>The Custom Field5.</value>
		public String CustomField5 { get; set; }

		/// <summary>
        /// Gets or sets the Custom Field6. Reserved property for custom field
        /// </summary>
        /// <value>The Custom Field6.</value>
		public String CustomField6 { get; set; }

		/// <summary>
        /// Gets or sets the Custom Field7. Reserved property for custom field
        /// </summary>
        /// <value>The Custom Field7.</value>
		public String CustomField7 { get; set; }

		/// <summary>
        /// Gets or sets the Custom Field8. Reserved property for custom field
        /// </summary>
        /// <value>The Custom Field8.</value>
		public String CustomField8 { get; set; }

		/// <summary>
        /// Gets or sets the Custom Field9. Reserved property for custom field
        /// </summary>
        /// <value>The Custom Field9.</value>
		public String CustomField9 { get; set; }

		/// <summary>
        /// Gets or sets the Custom Field10. Reserved property for custom field
        /// </summary>
        /// <value>The Custom Field10.</value>
		public String CustomField10 { get; set; }

		/// <summary>
        /// Gets or sets the Custom Field11. Reserved property for custom field
        /// </summary>
        /// <value>The Custom Field11.</value>
		public String CustomField11 { get; set; }

		/// <summary>
        /// Gets or sets the Custom Field12. Reserved property for custom field
        /// </summary>
        /// <value>The Custom Field12.</value>
		public String CustomField12 { get; set; }

		/// <summary>
        /// Gets or sets the Custom Field13. Reserved property for custom field
        /// </summary>
        /// <value>The Custom Field13.</value>
		public String CustomField13 { get; set; }

		/// <summary>
        /// Gets or sets the Custom Field14. Reserved property for custom field
        /// </summary>
        /// <value>The Custom Field14.</value>
		public String CustomField14 { get; set; }

		/// <summary>
        /// Gets or sets the Custom Field15. Reserved property for custom field
        /// </summary>
        /// <value>The Custom Field15.</value>
		public String CustomField15 { get; set; }

		/// <summary>
        /// Gets or sets the Is Active. Defines whether project active or archived
        /// </summary>
        /// <value>The Is Active.</value>
		public Boolean? IsActive { get; set; }

		/// <summary>
        /// Gets or sets the Delete Date. If DeleteDate not null project is deleted and will not be retreived from database by default. Projects are not actually deleted from database in TargetProcess
        /// </summary>
        /// <value>The Delete Date.</value>
		public DateTime? DeleteDate { get; set; }

		/// <summary>
        /// Gets or sets the Source Control Type. Type of source control. Currently only Subversion supported
        /// </summary>
        /// <value>The Source Control Type.</value>
		public SourceControlTypeEnum? SourceControlType { get; set; }

		/// <summary>
        /// Gets or sets the SCConnection String. Full path to the project in repository. For example: svn://myrep/myproj
        /// </summary>
        /// <value>The SCConnection String.</value>
		public String SCConnectionString { get; set; }

		/// <summary>
        /// Gets or sets the SCUser. Source control user.
        /// </summary>
        /// <value>The SCUser.</value>
		public String SCUser { get; set; }

		/// <summary>
        /// Gets or sets the SCPassword. Source control user's password.
        /// </summary>
        /// <value>The SCPassword.</value>
		public String SCPassword { get; set; }

		/// <summary>
        /// Gets or sets the SCStarting Revision. Revision from which TargetProcess starts track changes and commits.
        /// </summary>
        /// <value>The SCStarting Revision.</value>
		public Int32? SCStartingRevision { get; set; }

		/// <summary>
        /// Gets or sets the Is Product. Is Product
        /// </summary>
        /// <value>The Is Product.</value>
		public Boolean? IsProduct { get; set; }

		/// <summary>
        /// Gets or sets the Inbound Mail Create Requests. Inbound Mail Create Requests
        /// </summary>
        /// <value>The Inbound Mail Create Requests.</value>
		public Boolean? InboundMailCreateRequests { get; set; }

		/// <summary>
        /// Gets or sets the Inbound Mail Automatical Email Check Time. Inbound Mail Automatical Email Check Time
        /// </summary>
        /// <value>The Inbound Mail Automatical Email Check Time.</value>
		public Int32? InboundMailAutomaticalEmailCheckTime { get; set; }

		/// <summary>
        /// Gets or sets the Is Inbound Mail Enabled. Is Inbound Mail Enabled
        /// </summary>
        /// <value>The Is Inbound Mail Enabled.</value>
		public Boolean? IsInboundMailEnabled { get; set; }

		/// <summary>
        /// Gets or sets the Inbound Mail Reply Address. The outgoing email will be sent from this address.
        /// </summary>
        /// <value>The Inbound Mail Reply Address.</value>
		public String InboundMailReplyAddress { get; set; }

		/// <summary>
        /// Gets or sets the Inbound Mail Auto Check. 
        /// </summary>
        /// <value>The Inbound Mail Auto Check.</value>
		public Boolean? InboundMailAutoCheck { get; set; }

		/// <summary>
        /// Gets or sets the Inbound Mail Server. POP3 or IMAP server name
        /// </summary>
        /// <value>The Inbound Mail Server.</value>
		public String InboundMailServer { get; set; }

		/// <summary>
        /// Gets or sets the Inbound Mail Port. Inbound Mail Port
        /// </summary>
        /// <value>The Inbound Mail Port.</value>
		public Int32? InboundMailPort { get; set; }

		/// <summary>
        /// Gets or sets the Inbound Mail Use SSL. Inbound Mail Use SSL
        /// </summary>
        /// <value>The Inbound Mail Use SSL.</value>
		public Boolean? InboundMailUseSSL { get; set; }

		/// <summary>
        /// Gets or sets the Inbound Mail Login. POP3 or IMAP server Login
        /// </summary>
        /// <value>The Inbound Mail Login.</value>
		public String InboundMailLogin { get; set; }

		/// <summary>
        /// Gets or sets the Inbound Mail Password. POP3 or IMAP server Password
        /// </summary>
        /// <value>The Inbound Mail Password.</value>
		public String InboundMailPassword { get; set; }

		/// <summary>
        /// Gets or sets the Inbound Mail Protocol. Inbound mail protocol: POP3 or IMAP
        /// </summary>
        /// <value>The Inbound Mail Protocol.</value>
		public String InboundMailProtocol { get; set; }
		
		/// <summary>
        /// Gets or sets the Last Comment User ID. User who added last comment
        /// </summary>
        /// <value>The Last Comment User ID.</value>
		[ForeignKey]
		public Int32? LastCommentUserID { get; set; }
		
		/// <summary>
        /// Gets or sets the Parent Project ID. Project which entity belongs to
        /// </summary>
        /// <value>The Parent Project ID.</value>
		[ForeignKey]
		public Int32? ParentProjectID { get; set; }
		
		/// <summary>
        /// Gets or sets the Owner ID. Person who added the entity
        /// </summary>
        /// <value>The Owner ID.</value>
		[ForeignKey]
		public Int32? OwnerID { get; set; }
		
		/// <summary>
        /// Gets or sets the Last Editor ID. Person who edited entity last time
        /// </summary>
        /// <value>The Last Editor ID.</value>
		[ForeignKey]
		public Int32? LastEditorID { get; set; }
		
		/// <summary>
        /// Gets or sets the Program Of Project ID. Program associated with project. Optional.
        /// </summary>
        /// <value>The Program Of Project ID.</value>
		[ForeignKey]
		public Int32? ProgramOfProjectID { get; set; }
		
		/// <summary>
        /// Gets or sets the Process ID. Process associated with project.
        /// </summary>
        /// <value>The Process ID.</value>
		[ForeignKey]
		public Int32? ProcessID { get; set; }
		
		/// <summary>
        /// Gets or sets the Company ID. 
        /// </summary>
        /// <value>The Company ID.</value>
		[ForeignKey]
		public Int32? CompanyID { get; set; }
		

		
		/// <summary>
        /// Gets or sets the Parent Project Name. Project which entity belongs to
        /// </summary>
        /// <value>The Parent Project Name.</value>
		[RelationName]
		public virtual string ParentProjectName { get; set; }
		
		/// <summary>
        /// Gets or sets the Entity Type Name. Type of the entity. For example, Bug, TestCase, Task
        /// </summary>
        /// <value>The Entity Type Name.</value>
		[RelationName]
		public virtual string EntityTypeName { get; set; }
		
		/// <summary>
        /// Gets or sets the Program Of Project Name. Program associated with project. Optional.
        /// </summary>
        /// <value>The Program Of Project Name.</value>
		[RelationName]
		public virtual string ProgramOfProjectName { get; set; }
		
		/// <summary>
        /// Gets or sets the Process Name. Process associated with project.
        /// </summary>
        /// <value>The Process Name.</value>
		[RelationName]
		public virtual string ProcessName { get; set; }
		
	}
	
	
	/// <summary>
    /// Project fields
    /// </summary>
	public enum ProjectField
	{
        /// <summary>
        /// Name
        /// </summary>		
		Name,
        /// <summary>
        /// Description
        /// </summary>		
		Description,
		/// <summary>
		/// Abbreviation
		/// </summary>		
        Abbreviation,
		/// <summary>
        /// Start Date
        /// </summary>		
		StartDate,
        /// <summary>
        /// End Date
        /// </summary>		
		EndDate,
        /// <summary>
        /// Create Date
        /// </summary>		
		CreateDate,
        /// <summary>
        /// Modify Date
        /// </summary>		
		ModifyDate,
        /// <summary>
        /// Last Comment Date
        /// </summary>		
		LastCommentDate,
        /// <summary>
        /// Numeric Priority
        /// </summary>		
		NumericPriority,
        /// <summary>
        /// Custom Field1
        /// </summary>		
		CustomField1,
        /// <summary>
        /// Custom Field2
        /// </summary>		
		CustomField2,
        /// <summary>
        /// Custom Field3
        /// </summary>		
		CustomField3,
        /// <summary>
        /// Custom Field4
        /// </summary>		
		CustomField4,
        /// <summary>
        /// Custom Field5
        /// </summary>		
		CustomField5,
        /// <summary>
        /// Custom Field6
        /// </summary>		
		CustomField6,
        /// <summary>
        /// Custom Field7
        /// </summary>		
		CustomField7,
        /// <summary>
        /// Custom Field8
        /// </summary>		
		CustomField8,
        /// <summary>
        /// Custom Field9
        /// </summary>		
		CustomField9,
        /// <summary>
        /// Custom Field10
        /// </summary>		
		CustomField10,
        /// <summary>
        /// Custom Field11
        /// </summary>		
		CustomField11,
        /// <summary>
        /// Custom Field12
        /// </summary>		
		CustomField12,
        /// <summary>
        /// Custom Field13
        /// </summary>		
		CustomField13,
        /// <summary>
        /// Custom Field14
        /// </summary>		
		CustomField14,
        /// <summary>
        /// Custom Field15
        /// </summary>		
		CustomField15,
        /// <summary>
        /// Is Active
        /// </summary>		
		IsActive,
        /// <summary>
        /// Delete Date
        /// </summary>		
		DeleteDate,
        /// <summary>
        /// Source Control Type
        /// </summary>		
		SourceControlType,
        /// <summary>
        /// SCConnection String
        /// </summary>		
		SCConnectionString,
        /// <summary>
        /// SCUser
        /// </summary>		
		SCUser,
        /// <summary>
        /// SCPassword
        /// </summary>		
		SCPassword,
        /// <summary>
        /// SCStarting Revision
        /// </summary>		
		SCStartingRevision,
        /// <summary>
        /// Is Product
        /// </summary>		
		IsProduct,
        /// <summary>
        /// Inbound Mail Create Requests
        /// </summary>		
		InboundMailCreateRequests,
        /// <summary>
        /// Inbound Mail Automatical Email Check Time
        /// </summary>		
		InboundMailAutomaticalEmailCheckTime,
        /// <summary>
        /// Is Inbound Mail Enabled
        /// </summary>		
		IsInboundMailEnabled,
        /// <summary>
        /// Inbound Mail Reply Address
        /// </summary>		
		InboundMailReplyAddress,
        /// <summary>
        /// Inbound Mail Auto Check
        /// </summary>		
		InboundMailAutoCheck,
        /// <summary>
        /// Inbound Mail Server
        /// </summary>		
		InboundMailServer,
        /// <summary>
        /// Inbound Mail Port
        /// </summary>		
		InboundMailPort,
        /// <summary>
        /// Inbound Mail Use SSL
        /// </summary>		
		InboundMailUseSSL,
        /// <summary>
        /// Inbound Mail Login
        /// </summary>		
		InboundMailLogin,
        /// <summary>
        /// Inbound Mail Password
        /// </summary>		
		InboundMailPassword,
        /// <summary>
        /// Inbound Mail Protocol
        /// </summary>		
		InboundMailProtocol,
        /// <summary>
        /// Last Comment User ID
        /// </summary>		
		LastCommentUserID,
        /// <summary>
        /// Parent Project ID
        /// </summary>		
		ParentProjectID,
        /// <summary>
        /// Owner ID
        /// </summary>		
		OwnerID,
        /// <summary>
        /// Last Editor ID
        /// </summary>		
		LastEditorID,
        /// <summary>
        /// Program Of Project ID
        /// </summary>		
		ProgramOfProjectID,
        /// <summary>
        /// Process ID
        /// </summary>		
		ProcessID,
        /// <summary>
        /// Company ID
        /// </summary>		
		CompanyID,
        /// <summary>
        /// Parent Project Name
        /// </summary>		
		ParentProjectName,
        /// <summary>
        /// Entity Type Name
        /// </summary>		
		EntityTypeName,
        /// <summary>
        /// Program Of Project Name
        /// </summary>		
		ProgramOfProjectName,
        /// <summary>
        /// Process Name
        /// </summary>		
		ProcessName,
	}
}