//-----------------------------------------------------------------------------
// This code was generated by a tool.
// Changes to this file will be lost if the code is regenerated.
//-----------------------------------------------------------------------------
using System;
using Tp.Integration.Common;

namespace Tp.Integration.Common
{
    /// <summary>
    /// Data Transfer object of Request General. Represents the relation between request and general.
	/// TargetProcess system usage only
    /// </summary>
	[Serializable]
	public partial class RequestGeneralDTO : DataTransferObject
	{
        /// <summary>
        /// Gets or sets the ID.
        /// </summary>
        /// <value>The ID.</value>		
		[PrimaryKey]
		public override int? ID
		{
			get { return RequestGeneralID; }
			set
			{
				if (value == int.MinValue)
					value = null;

				RequestGeneralID = value;
			}
		}

        /// <summary>
        /// Gets or sets the Request General ID.
        /// </summary>
        /// <value>The Request General ID.</value>
		[PrimaryKey]
		public int? RequestGeneralID { get; set; }
		

		/// <summary>
        /// Gets or sets the Create Date. The creation date of relation
        /// </summary>
        /// <value>The Create Date.</value>
		public DateTime? CreateDate { get; set; }

		/// <summary>
        /// Gets or sets the Is Attached. Indicates that existing general is attached to request
        /// </summary>
        /// <value>The Is Attached.</value>
		public Boolean? IsAttached { get; set; }
		
		/// <summary>
        /// Gets or sets the General ID. Reference to general entity
        /// </summary>
        /// <value>The General ID.</value>
		[ForeignKey]
		public Int32? GeneralID { get; set; }
		
		/// <summary>
        /// Gets or sets the Request ID. Reference to request
        /// </summary>
        /// <value>The Request ID.</value>
		[ForeignKey]
		public Int32? RequestID { get; set; }
		

		
		/// <summary>
        /// Gets or sets the General Name. Reference to general entity
        /// </summary>
        /// <value>The General Name.</value>
		[RelationName]
		public virtual string GeneralName { get; set; }
		
		/// <summary>
        /// Gets or sets the Request Name. Reference to request
        /// </summary>
        /// <value>The Request Name.</value>
		[RelationName]
		public virtual string RequestName { get; set; }
		
	}
	
	
	/// <summary>
    /// Request General fields
    /// </summary>
	public enum RequestGeneralField
	{
        /// <summary>
        /// Create Date
        /// </summary>		
		CreateDate,
        /// <summary>
        /// Is Attached
        /// </summary>		
		IsAttached,
        /// <summary>
        /// General ID
        /// </summary>		
		GeneralID,
        /// <summary>
        /// Request ID
        /// </summary>		
		RequestID,
        /// <summary>
        /// General Name
        /// </summary>		
		GeneralName,
        /// <summary>
        /// Request Name
        /// </summary>		
		RequestName,
	}
}