//-----------------------------------------------------------------------------
// This code was generated by a tool.
// Changes to this file will be lost if the code is regenerated.
//-----------------------------------------------------------------------------
using System;
using System.Xml.Serialization;using System.Runtime.Serialization;
using Tp.Integration.Common;

namespace Tp.Integration.Common
{
    /// <summary>
    /// Data Transfer object of Revision. Represents revision from source control repository..
    /// </summary>
	[Serializable][DataContract]
	public partial class RevisionDTO : DataTransferObject
	{
        /// <summary>
        /// Gets or sets the ID.
        /// </summary>
        /// <value>The ID.</value>		
		[PrimaryKey]
		public override int? ID
		{
			get { return RevisionID; }
			set
			{
				if (value == int.MinValue)
					value = null;

				RevisionID = value;
			}
		}

        /// <summary>
        /// Gets or sets the Revision ID.
        /// </summary>
        /// <value>The Revision ID.</value>
		[PrimaryKey]
		[DataMember][XmlElement(Order = 3)]public int? RevisionID { get; set; }
		

		/// <summary>
        /// Gets or sets the Source Control ID. Source control identifier. 1 for Subversion
        /// </summary>
        /// <value>The Source Control ID.</value>
		[DataMember][XmlElement(Order = 4)]public string SourceControlID { get; set; }

		/// <summary>
        /// Gets or sets the Commit Date. Date when revision has been commited into repository.
        /// </summary>
        /// <value>The Commit Date.</value>
		[DataMember][XmlElement(Order = 5)]public DateTime? CommitDate { get; set; }

		/// <summary>
        /// Gets or sets the Plugin Profile ID. 
        /// </summary>
        /// <value>The Plugin Profile ID.</value>
		[DataMember][XmlElement(Order = 6)]public Int32? PluginProfileID { get; set; }

		/// <summary>
        /// Gets or sets the Description. Revision message.
        /// </summary>
        /// <value>The Description.</value>
		[DataMember][XmlElement(Order = 7)]public String Description { get; set; }
		
		/// <summary>
        /// Gets or sets the Project ID. Project to which revision belongs.
        /// </summary>
        /// <value>The Project ID.</value>
		[ForeignKey]
		[DataMember][XmlElement(Order = 8)]public Int32? ProjectID { get; set; }
		
		/// <summary>
        /// Gets or sets the Author ID. Person who commit revision.
        /// </summary>
        /// <value>The Author ID.</value>
		[ForeignKey]
		[DataMember][XmlElement(Order = 9)]public Int32? AuthorID { get; set; }
		

		
		/// <summary>
        /// Gets or sets the Project Name. Project to which revision belongs.
        /// </summary>
        /// <value>The Project Name.</value>
		[RelationName]
		[DataMember][XmlElement(Order = 10)]public virtual string ProjectName { get; set; }
		
	}
	
	
	/// <summary>
    /// Revision fields
    /// </summary>
	public enum RevisionField
	{
        /// <summary>
        /// Source Control ID
        /// </summary>		
		SourceControlID,
        /// <summary>
        /// Commit Date
        /// </summary>		
		CommitDate,
        /// <summary>
        /// Plugin Profile ID
        /// </summary>		
		PluginProfileID,
        /// <summary>
        /// Description
        /// </summary>		
		Description,
        /// <summary>
        /// Project ID
        /// </summary>		
		ProjectID,
        /// <summary>
        /// Author ID
        /// </summary>		
		AuthorID,
        /// <summary>
        /// Project Name
        /// </summary>		
		ProjectName,
	}
}
