//-----------------------------------------------------------------------------
// This code was generated by a tool.
// Changes to this file will be lost if the code is regenerated.
//-----------------------------------------------------------------------------
using System;
using System.Xml.Serialization;using System.Runtime.Serialization;
using Tp.Integration.Common;

namespace Tp.Integration.Common
{
    /// <summary>
    /// Data Transfer object of Revision Assignable. Relation between assignable and revision.
	/// TargetProcess system usage only
    /// </summary>
	[Serializable][DataContract]
	public partial class RevisionAssignableDTO : DataTransferObject
	{
        /// <summary>
        /// Gets or sets the ID.
        /// </summary>
        /// <value>The ID.</value>		
		[PrimaryKey]
		public override int? ID
		{
			get { return RevisionAssignableID; }
			set
			{
				if (value == int.MinValue)
					value = null;

				RevisionAssignableID = value;
			}
		}

        /// <summary>
        /// Gets or sets the Revision Assignable ID.
        /// </summary>
        /// <value>The Revision Assignable ID.</value>
		[PrimaryKey]
		[DataMember][XmlElement(Order = 3)]public int? RevisionAssignableID { get; set; }
		
		
		/// <summary>
        /// Gets or sets the Assignable ID. Reference to assignable
        /// </summary>
        /// <value>The Assignable ID.</value>
		[ForeignKey]
		[DataMember][XmlElement(Order = 4)]public Int32? AssignableID { get; set; }
		
		/// <summary>
        /// Gets or sets the Revision ID. Reference to revision
        /// </summary>
        /// <value>The Revision ID.</value>
		[ForeignKey]
		[DataMember][XmlElement(Order = 5)]public Int32? RevisionID { get; set; }
		

		
		/// <summary>
        /// Gets or sets the Assignable Name. Reference to assignable
        /// </summary>
        /// <value>The Assignable Name.</value>
		[RelationName]
		[DataMember][XmlElement(Order = 6)]public virtual string AssignableName { get; set; }
		
	}
	
	
	/// <summary>
    /// Revision Assignable fields
    /// </summary>
	public enum RevisionAssignableField
	{
        /// <summary>
        /// Assignable ID
        /// </summary>		
		AssignableID,
        /// <summary>
        /// Revision ID
        /// </summary>		
		RevisionID,
        /// <summary>
        /// Assignable Name
        /// </summary>		
		AssignableName,
	}
}
