//-----------------------------------------------------------------------------
// This code was generated by a tool.
// Changes to this file will be lost if the code is regenerated.
//-----------------------------------------------------------------------------
using System;
using System.Xml.Serialization;using System.Runtime.Serialization;
using Tp.Integration.Common;

namespace Tp.Integration.Common
{
    /// <summary>
    /// Data Transfer object of Saved Filter. Saved filter.
	/// TargetProcess system usage only
    /// </summary>
	[Serializable][DataContract]
	public partial class SavedFilterDTO : DataTransferObject
	{
        /// <summary>
        /// Gets or sets the ID.
        /// </summary>
        /// <value>The ID.</value>		
		[PrimaryKey]
		public override int? ID
		{
			get { return SavedFilterID; }
			set
			{
				if (value == int.MinValue)
					value = null;

				SavedFilterID = value;
			}
		}

        /// <summary>
        /// Gets or sets the Saved Filter ID.
        /// </summary>
        /// <value>The Saved Filter ID.</value>
		[PrimaryKey]
		[DataMember][XmlElement(Order = 3)]public int? SavedFilterID { get; set; }
		

		/// <summary>
        /// Gets or sets the Name. The name of the filter
        /// </summary>
        /// <value>The Name.</value>
		[DataMember][XmlElement(Order = 4)]public String Name { get; set; }

		/// <summary>
        /// Gets or sets the Description. The description of the filter
        /// </summary>
        /// <value>The Description.</value>
		[DataMember][XmlElement(Order = 5)]public String Description { get; set; }

		/// <summary>
        /// Gets or sets the Filter Type. The type of the filter
        /// </summary>
        /// <value>The Filter Type.</value>
		[DataMember][XmlElement(Order = 6)]public String FilterType { get; set; }

		/// <summary>
        /// Gets or sets the Is Default. Indicates that the filter is default
        /// </summary>
        /// <value>The Is Default.</value>
		[DataMember][XmlElement(Order = 7)]public Boolean? IsDefault { get; set; }

		/// <summary>
        /// Gets or sets the Is Public. 
        /// </summary>
        /// <value>The Is Public.</value>
		[DataMember][XmlElement(Order = 8)]public Boolean? IsPublic { get; set; }

		/// <summary>
        /// Gets or sets the Query Filter. Serialized value
        /// </summary>
        /// <value>The Query Filter.</value>
		[DataMember][XmlElement(Order = 9)]public String QueryFilter { get; set; }

		/// <summary>
        /// Gets or sets the Project ID. Reference to project
        /// </summary>
        /// <value>The Project ID.</value>
		[DataMember][XmlElement(Order = 10)]public Int32? ProjectID { get; set; }
		
		/// <summary>
        /// Gets or sets the Owner ID. The owner of the filter
        /// </summary>
        /// <value>The Owner ID.</value>
		[ForeignKey]
		[DataMember][XmlElement(Order = 11)]public Int32? OwnerID { get; set; }
		

		
	}
	
	
	/// <summary>
    /// Saved Filter fields
    /// </summary>
	public enum SavedFilterField
	{
        /// <summary>
        /// Name
        /// </summary>		
		Name,
        /// <summary>
        /// Description
        /// </summary>		
		Description,
        /// <summary>
        /// Filter Type
        /// </summary>		
		FilterType,
        /// <summary>
        /// Is Default
        /// </summary>		
		IsDefault,
        /// <summary>
        /// Is Public
        /// </summary>		
		IsPublic,
        /// <summary>
        /// Query Filter
        /// </summary>		
		QueryFilter,
        /// <summary>
        /// Project ID
        /// </summary>		
		ProjectID,
        /// <summary>
        /// Owner ID
        /// </summary>		
		OwnerID,
	}
}
