//-----------------------------------------------------------------------------
// This code was generated by a tool.
// Changes to this file will be lost if the code is regenerated.
//-----------------------------------------------------------------------------
using System;
using Tp.Integration.Common;

namespace Tp.Integration.Common
{
    /// <summary>
    /// Data Transfer object of Tag General. Represents Tag General relation.
	/// TargetProcess system usage only
    /// </summary>
	[Serializable]
	public partial class TagGeneralDTO : DataTransferObject
	{
        /// <summary>
        /// Gets or sets the ID.
        /// </summary>
        /// <value>The ID.</value>		
		[PrimaryKey]
		public override int? ID
		{
			get { return TagGeneralID; }
			set
			{
				if (value == int.MinValue)
					value = null;

				TagGeneralID = value;
			}
		}

        /// <summary>
        /// Gets or sets the Tag General ID.
        /// </summary>
        /// <value>The Tag General ID.</value>
		[PrimaryKey]
		public int? TagGeneralID { get; set; }
		
		
		/// <summary>
        /// Gets or sets the General ID. Reference to General
        /// </summary>
        /// <value>The General ID.</value>
		[ForeignKey]
		public Int32? GeneralID { get; set; }
		
		/// <summary>
        /// Gets or sets the Tag ID. Reference to Tag
        /// </summary>
        /// <value>The Tag ID.</value>
		[ForeignKey]
		public Int32? TagID { get; set; }
		

		
		/// <summary>
        /// Gets or sets the General Name. Reference to General
        /// </summary>
        /// <value>The General Name.</value>
		[RelationName]
		public virtual string GeneralName { get; set; }
		
		/// <summary>
        /// Gets or sets the Tag Name. Reference to Tag
        /// </summary>
        /// <value>The Tag Name.</value>
		[RelationName]
		public virtual string TagName { get; set; }
		
	}
	
	
	/// <summary>
    /// Tag General fields
    /// </summary>
	public enum TagGeneralField
	{
        /// <summary>
        /// General ID
        /// </summary>		
		GeneralID,
        /// <summary>
        /// Tag ID
        /// </summary>		
		TagID,
        /// <summary>
        /// General Name
        /// </summary>		
		GeneralName,
        /// <summary>
        /// Tag Name
        /// </summary>		
		TagName,
	}
}