//-----------------------------------------------------------------------------
// This code was generated by a tool.
// Changes to this file will be lost if the code is regenerated.
//-----------------------------------------------------------------------------
using System;
using Tp.Integration.Common;

namespace Tp.Integration.Common
{
    /// <summary>
    /// Data Transfer object of Team List Item. 
	/// TargetProcess system usage only
    /// </summary>
	[Serializable]
	public partial class TeamListItemDTO : DataTransferObject
	{
        /// <summary>
        /// Gets or sets the ID.
        /// </summary>
        /// <value>The ID.</value>		
		[PrimaryKey]
		public override int? ID
		{
			get { return TeamID; }
			set
			{
				if (value == int.MinValue)
					value = null;

				TeamID = value;
			}
		}

        /// <summary>
        /// Gets or sets the Team ID.
        /// </summary>
        /// <value>The Team ID.</value>
		[PrimaryKey]
		public int? TeamID { get; set; }
		

		/// <summary>
        /// Gets or sets the Role ID. 
        /// </summary>
        /// <value>The Role ID.</value>
		public Int32? RoleID { get; set; }

		/// <summary>
        /// Gets or sets the User ID. 
        /// </summary>
        /// <value>The User ID.</value>
		public Int32? UserID { get; set; }

		/// <summary>
        /// Gets or sets the Assignable ID. 
        /// </summary>
        /// <value>The Assignable ID.</value>
		public Int32? AssignableID { get; set; }
		

		
	}
	
	
	/// <summary>
    /// Team List Item fields
    /// </summary>
	public enum TeamListItemField
	{
        /// <summary>
        /// Role ID
        /// </summary>		
		RoleID,
        /// <summary>
        /// User ID
        /// </summary>		
		UserID,
        /// <summary>
        /// Assignable ID
        /// </summary>		
		AssignableID,
	}
}