//-----------------------------------------------------------------------------
// This code was generated by a tool.
// Changes to this file will be lost if the code is regenerated.
//-----------------------------------------------------------------------------
using System;
using Tp.Integration.Common;

namespace Tp.Integration.Common
{
    /// <summary>
    /// Data Transfer object of Team. Team is Person-Assignable binding in the system. Person assigned to the entity via Team object..
    /// </summary>
	[Serializable]
	public partial class TeamDTO : DataTransferObject
	{
        /// <summary>
        /// Gets or sets the ID.
        /// </summary>
        /// <value>The ID.</value>		
		[PrimaryKey]
		public override int? ID
		{
			get { return TeamID; }
			set
			{
				if (value == int.MinValue)
					value = null;

				TeamID = value;
			}
		}

        /// <summary>
        /// Gets or sets the Team ID.
        /// </summary>
        /// <value>The Team ID.</value>
		[PrimaryKey]
		public int? TeamID { get; set; }
		
		
		/// <summary>
        /// Gets or sets the Assignable ID. Reference to entity to which person assigned
        /// </summary>
        /// <value>The Assignable ID.</value>
		[ForeignKey]
		public Int32? AssignableID { get; set; }
		
		/// <summary>
        /// Gets or sets the User ID. Reference to assigned person
        /// </summary>
        /// <value>The User ID.</value>
		[ForeignKey]
		public Int32? UserID { get; set; }
		
		/// <summary>
        /// Gets or sets the Role ID. Role is a 'role' in entity workflow. For example, we may assign Teddy Bear as Developer to user story. Developer is an Role in this case.
        /// </summary>
        /// <value>The Role ID.</value>
		[ForeignKey]
		public Int32? RoleID { get; set; }
		

		
		/// <summary>
        /// Gets or sets the Assignable Name. Reference to entity to which person assigned
        /// </summary>
        /// <value>The Assignable Name.</value>
		[RelationName]
		public virtual string AssignableName { get; set; }
		
		/// <summary>
        /// Gets or sets the Role Name. Role is a 'role' in entity workflow. For example, we may assign Teddy Bear as Developer to user story. Developer is an Role in this case.
        /// </summary>
        /// <value>The Role Name.</value>
		[RelationName]
		public virtual string RoleName { get; set; }
		
	}
	
	
	/// <summary>
    /// Team fields
    /// </summary>
	public enum TeamField
	{
        /// <summary>
        /// Assignable ID
        /// </summary>		
		AssignableID,
        /// <summary>
        /// User ID
        /// </summary>		
		UserID,
        /// <summary>
        /// Role ID
        /// </summary>		
		RoleID,
        /// <summary>
        /// Assignable Name
        /// </summary>		
		AssignableName,
        /// <summary>
        /// Role Name
        /// </summary>		
		RoleName,
	}
}