//-----------------------------------------------------------------------------
// This code was generated by a tool.
// Changes to this file will be lost if the code is regenerated.
//-----------------------------------------------------------------------------
using System;
using System.Xml.Serialization;
using Tp.Integration.Common;

namespace Tp.Integration.Common
{
    /// <summary>
    /// Data Transfer object of Test Case Test Plan. Releation between test case and test plan.
	/// TargetProcess system usage only
    /// </summary>
	[Serializable]
	public partial class TestCaseTestPlanDTO : DataTransferObject
	{
        /// <summary>
        /// Gets or sets the ID.
        /// </summary>
        /// <value>The ID.</value>		
		[PrimaryKey]
		public override int? ID
		{
			get { return TestCaseTestPlanID; }
			set
			{
				if (value == int.MinValue)
					value = null;

				TestCaseTestPlanID = value;
			}
		}

        /// <summary>
        /// Gets or sets the Test Case Test Plan ID.
        /// </summary>
        /// <value>The Test Case Test Plan ID.</value>
		[PrimaryKey]
		[XmlElement(Order = 3)]public int? TestCaseTestPlanID { get; set; }
		
		
		/// <summary>
        /// Gets or sets the Test Plan ID. Reference to test plan
        /// </summary>
        /// <value>The Test Plan ID.</value>
		[ForeignKey]
		[XmlElement(Order = 4)]public Int32? TestPlanID { get; set; }
		
		/// <summary>
        /// Gets or sets the Test Case ID. Reference to test case
        /// </summary>
        /// <value>The Test Case ID.</value>
		[ForeignKey]
		[XmlElement(Order = 5)]public Int32? TestCaseID { get; set; }
		

		
		/// <summary>
        /// Gets or sets the Test Plan Name. Reference to test plan
        /// </summary>
        /// <value>The Test Plan Name.</value>
		[RelationName]
		[XmlElement(Order = 6)]public virtual string TestPlanName { get; set; }
		
		/// <summary>
        /// Gets or sets the Test Case Name. Reference to test case
        /// </summary>
        /// <value>The Test Case Name.</value>
		[RelationName]
		[XmlElement(Order = 7)]public virtual string TestCaseName { get; set; }
		
	}
	
	
	/// <summary>
    /// Test Case Test Plan fields
    /// </summary>
	public enum TestCaseTestPlanField
	{
        /// <summary>
        /// Test Plan ID
        /// </summary>		
		TestPlanID,
        /// <summary>
        /// Test Case ID
        /// </summary>		
		TestCaseID,
        /// <summary>
        /// Test Plan Name
        /// </summary>		
		TestPlanName,
        /// <summary>
        /// Test Case Name
        /// </summary>		
		TestCaseName,
	}
}
