//-----------------------------------------------------------------------------
// This code was generated by a tool.
// Changes to this file will be lost if the code is regenerated.
//-----------------------------------------------------------------------------
using System;
using System.Xml.Serialization;
using Tp.Integration.Common;

namespace Tp.Integration.Common
{
    /// <summary>
    /// Data Transfer object of Time. Represents Time.
    /// </summary>
	[Serializable]
	public partial class TimeDTO : DataTransferObject
	{
        /// <summary>
        /// Gets or sets the ID.
        /// </summary>
        /// <value>The ID.</value>		
		[PrimaryKey]
		public override int? ID
		{
			get { return TimeID; }
			set
			{
				if (value == int.MinValue)
					value = null;

				TimeID = value;
			}
		}

        /// <summary>
        /// Gets or sets the Time ID.
        /// </summary>
        /// <value>The Time ID.</value>
		[PrimaryKey]
		[XmlElement(Order = 3)]public int? TimeID { get; set; }
		

		/// <summary>
        /// Gets or sets the Description. Description
        /// </summary>
        /// <value>The Description.</value>
		[XmlElement(Order = 4)]public String Description { get; set; }

		/// <summary>
        /// Gets or sets the Spent. Spent
        /// </summary>
        /// <value>The Spent.</value>
		[XmlElement(Order = 5)]public Decimal? Spent { get; set; }

		/// <summary>
        /// Gets or sets the Remain. Remain
        /// </summary>
        /// <value>The Remain.</value>
		[XmlElement(Order = 6)]public Decimal? Remain { get; set; }

		/// <summary>
        /// Gets or sets the Create Date. 
        /// </summary>
        /// <value>The Create Date.</value>
		[XmlElement(Order = 7)]public DateTime? CreateDate { get; set; }

		/// <summary>
        /// Gets or sets the Spent Date. Spent Date
        /// </summary>
        /// <value>The Spent Date.</value>
		[XmlElement(Order = 8)]public DateTime? SpentDate { get; set; }

		/// <summary>
        /// Gets or sets the Estimation. Estimation
        /// </summary>
        /// <value>The Estimation.</value>
		[XmlElement(Order = 9)]public Boolean? Estimation { get; set; }

		/// <summary>
        /// Gets or sets the Custom Field1. Reserved property for custom field
        /// </summary>
        /// <value>The Custom Field1.</value>
		[XmlElement(Order = 10)]public String CustomField1 { get; set; }

		/// <summary>
        /// Gets or sets the Custom Field2. Reserved property for custom field
        /// </summary>
        /// <value>The Custom Field2.</value>
		[XmlElement(Order = 11)]public String CustomField2 { get; set; }

		/// <summary>
        /// Gets or sets the Custom Field3. Reserved property for custom field
        /// </summary>
        /// <value>The Custom Field3.</value>
		[XmlElement(Order = 12)]public String CustomField3 { get; set; }

		/// <summary>
        /// Gets or sets the Custom Field4. Reserved property for custom field
        /// </summary>
        /// <value>The Custom Field4.</value>
		[XmlElement(Order = 13)]public String CustomField4 { get; set; }

		/// <summary>
        /// Gets or sets the Custom Field5. Reserved property for custom field
        /// </summary>
        /// <value>The Custom Field5.</value>
		[XmlElement(Order = 14)]public String CustomField5 { get; set; }

		/// <summary>
        /// Gets or sets the Custom Field6. Reserved property for custom field
        /// </summary>
        /// <value>The Custom Field6.</value>
		[XmlElement(Order = 15)]public String CustomField6 { get; set; }

		/// <summary>
        /// Gets or sets the Custom Field7. Reserved property for custom field
        /// </summary>
        /// <value>The Custom Field7.</value>
		[XmlElement(Order = 16)]public String CustomField7 { get; set; }

		/// <summary>
        /// Gets or sets the Custom Field8. Reserved property for custom field
        /// </summary>
        /// <value>The Custom Field8.</value>
		[XmlElement(Order = 17)]public String CustomField8 { get; set; }

		/// <summary>
        /// Gets or sets the Custom Field9. Reserved property for custom field
        /// </summary>
        /// <value>The Custom Field9.</value>
		[XmlElement(Order = 18)]public String CustomField9 { get; set; }

		/// <summary>
        /// Gets or sets the Custom Field10. Reserved property for custom field
        /// </summary>
        /// <value>The Custom Field10.</value>
		[XmlElement(Order = 19)]public String CustomField10 { get; set; }

		/// <summary>
        /// Gets or sets the Custom Field11. Reserved property for custom field
        /// </summary>
        /// <value>The Custom Field11.</value>
		[XmlElement(Order = 20)]public String CustomField11 { get; set; }

		/// <summary>
        /// Gets or sets the Custom Field12. Reserved property for custom field
        /// </summary>
        /// <value>The Custom Field12.</value>
		[XmlElement(Order = 21)]public String CustomField12 { get; set; }

		/// <summary>
        /// Gets or sets the Custom Field13. Reserved property for custom field
        /// </summary>
        /// <value>The Custom Field13.</value>
		[XmlElement(Order = 22)]public String CustomField13 { get; set; }

		/// <summary>
        /// Gets or sets the Custom Field14. Reserved property for custom field
        /// </summary>
        /// <value>The Custom Field14.</value>
		[XmlElement(Order = 23)]public String CustomField14 { get; set; }

		/// <summary>
        /// Gets or sets the Custom Field15. Reserved property for custom field
        /// </summary>
        /// <value>The Custom Field15.</value>
		[XmlElement(Order = 24)]public String CustomField15 { get; set; }
		
		/// <summary>
        /// Gets or sets the Project ID. Reference to Project
        /// </summary>
        /// <value>The Project ID.</value>
		[ForeignKey]
		[XmlElement(Order = 25)]public Int32? ProjectID { get; set; }
		
		/// <summary>
        /// Gets or sets the User ID. Reference to owner
        /// </summary>
        /// <value>The User ID.</value>
		[ForeignKey]
		[XmlElement(Order = 26)]public Int32? UserID { get; set; }
		
		/// <summary>
        /// Gets or sets the Assignable ID. Reference to assignable
        /// </summary>
        /// <value>The Assignable ID.</value>
		[ForeignKey]
		[XmlElement(Order = 27)]public Int32? AssignableID { get; set; }
		
		/// <summary>
        /// Gets or sets the Custom Activity ID. Reference to custom activity
        /// </summary>
        /// <value>The Custom Activity ID.</value>
		[ForeignKey]
		[XmlElement(Order = 28)]public Int32? CustomActivityID { get; set; }
		
		/// <summary>
        /// Gets or sets the Role ID. Rerefence to role
        /// </summary>
        /// <value>The Role ID.</value>
		[ForeignKey]
		[XmlElement(Order = 29)]public Int32? RoleID { get; set; }
		

		
		/// <summary>
        /// Gets or sets the Project Name. Reference to Project
        /// </summary>
        /// <value>The Project Name.</value>
		[RelationName]
		[XmlElement(Order = 30)]public virtual string ProjectName { get; set; }
		
		/// <summary>
        /// Gets or sets the Assignable Name. Reference to assignable
        /// </summary>
        /// <value>The Assignable Name.</value>
		[RelationName]
		[XmlElement(Order = 31)]public virtual string AssignableName { get; set; }
		
		/// <summary>
        /// Gets or sets the Custom Activity Name. Reference to custom activity
        /// </summary>
        /// <value>The Custom Activity Name.</value>
		[RelationName]
		[XmlElement(Order = 32)]public virtual string CustomActivityName { get; set; }
		
		/// <summary>
        /// Gets or sets the Role Name. Rerefence to role
        /// </summary>
        /// <value>The Role Name.</value>
		[RelationName]
		[XmlElement(Order = 33)]public virtual string RoleName { get; set; }
		
	}
	
	
	/// <summary>
    /// Time fields
    /// </summary>
	public enum TimeField
	{
        /// <summary>
        /// Description
        /// </summary>		
		Description,
        /// <summary>
        /// Spent
        /// </summary>		
		Spent,
        /// <summary>
        /// Remain
        /// </summary>		
		Remain,
        /// <summary>
        /// Create Date
        /// </summary>		
		CreateDate,
        /// <summary>
        /// Spent Date
        /// </summary>		
		SpentDate,
        /// <summary>
        /// Estimation
        /// </summary>		
		Estimation,
        /// <summary>
        /// Custom Field1
        /// </summary>		
		CustomField1,
        /// <summary>
        /// Custom Field2
        /// </summary>		
		CustomField2,
        /// <summary>
        /// Custom Field3
        /// </summary>		
		CustomField3,
        /// <summary>
        /// Custom Field4
        /// </summary>		
		CustomField4,
        /// <summary>
        /// Custom Field5
        /// </summary>		
		CustomField5,
        /// <summary>
        /// Custom Field6
        /// </summary>		
		CustomField6,
        /// <summary>
        /// Custom Field7
        /// </summary>		
		CustomField7,
        /// <summary>
        /// Custom Field8
        /// </summary>		
		CustomField8,
        /// <summary>
        /// Custom Field9
        /// </summary>		
		CustomField9,
        /// <summary>
        /// Custom Field10
        /// </summary>		
		CustomField10,
        /// <summary>
        /// Custom Field11
        /// </summary>		
		CustomField11,
        /// <summary>
        /// Custom Field12
        /// </summary>		
		CustomField12,
        /// <summary>
        /// Custom Field13
        /// </summary>		
		CustomField13,
        /// <summary>
        /// Custom Field14
        /// </summary>		
		CustomField14,
        /// <summary>
        /// Custom Field15
        /// </summary>		
		CustomField15,
        /// <summary>
        /// Project ID
        /// </summary>		
		ProjectID,
        /// <summary>
        /// User ID
        /// </summary>		
		UserID,
        /// <summary>
        /// Assignable ID
        /// </summary>		
		AssignableID,
        /// <summary>
        /// Custom Activity ID
        /// </summary>		
		CustomActivityID,
        /// <summary>
        /// Role ID
        /// </summary>		
		RoleID,
        /// <summary>
        /// Project Name
        /// </summary>		
		ProjectName,
        /// <summary>
        /// Assignable Name
        /// </summary>		
		AssignableName,
        /// <summary>
        /// Custom Activity Name
        /// </summary>		
		CustomActivityName,
        /// <summary>
        /// Role Name
        /// </summary>		
		RoleName,
	}
}
