//-----------------------------------------------------------------------------
// This code was generated by a tool.
// Changes to this file will be lost if the code is regenerated.
//-----------------------------------------------------------------------------
using System;
using System.Xml.Serialization;using System.Runtime.Serialization;
using Tp.Integration.Common;

namespace Tp.Integration.Common
{
    /// <summary>
    /// Data Transfer object of Tp Session. Represents Tp Session.
	/// TargetProcess system usage only
    /// </summary>
	[Serializable][DataContract]
	public partial class TpSessionDTO : DataTransferObject
	{
        /// <summary>
        /// Gets or sets the ID.
        /// </summary>
        /// <value>The ID.</value>		
		[PrimaryKey]
		public override int? ID
		{
			get { return TpSessionID; }
			set
			{
				if (value == int.MinValue)
					value = null;

				TpSessionID = value;
			}
		}

        /// <summary>
        /// Gets or sets the Tp Session ID.
        /// </summary>
        /// <value>The Tp Session ID.</value>
		[PrimaryKey]
		[DataMember][XmlElement(Order = 3)]public int? TpSessionID { get; set; }
		

		/// <summary>
        /// Gets or sets the User ID. User ID
        /// </summary>
        /// <value>The User ID.</value>
		[DataMember][XmlElement(Order = 4)]public Int32? UserID { get; set; }

		/// <summary>
        /// Gets or sets the Is Compressed. Is Compressed
        /// </summary>
        /// <value>The Is Compressed.</value>
		[DataMember][XmlElement(Order = 5)]public Boolean? IsCompressed { get; set; }

		/// <summary>
        /// Gets or sets the Obj Key. Obj Key
        /// </summary>
        /// <value>The Obj Key.</value>
		[DataMember][XmlElement(Order = 6)]public String ObjKey { get; set; }

		/// <summary>
        /// Gets or sets the Buffer. Buffer
        /// </summary>
        /// <value>The Buffer.</value>
		[DataMember][XmlElement(Order = 7)]public Byte[] Buffer { get; set; }

		/// <summary>
		/// Gets or sets the ModifyDate. ModifyDate
		/// </summary>
		/// <value>The ModifyDate.</value>
		[DataMember][XmlElement(Order = 8)]public DateTime? ModifyDate { get; set; }
		
	}
	
	
	/// <summary>
    /// Tp Session fields
    /// </summary>
	public enum TpSessionField
	{
        /// <summary>
        /// User ID
        /// </summary>		
		UserID,
        /// <summary>
        /// Is Compressed
        /// </summary>		
		IsCompressed,
        /// <summary>
        /// Obj Key
        /// </summary>		
		ObjKey,
        /// <summary>
        /// Buffer
        /// </summary>		
		Buffer,
		/// <summary>
		/// ModifyDate
		/// </summary>		
		ModifyDate,
	}
}
