// 
// THIS FILE IS AUTOGENERATED! ANY MANUAL MODIFICATIONS WILL BE LOST!
//

using System;
using Tp.Integration.Common;

namespace Tp.Integration.Messages.EntityLifecycle.Messages
{
	[Serializable]
	public class AttachmentCreatedMessage : EntityCreatedMessage<AttachmentDTO>, ISagaMessage
	{
	}

	[Serializable]
	public class AttachmentDeletedMessage : EntityDeletedMessage<AttachmentDTO>, ISagaMessage
	{
	}

	[Serializable]
	public class AttachmentUpdatedMessage : EntityUpdatedMessage<AttachmentDTO, AttachmentField>, ISagaMessage
	{
		
	}

}
