// 
// THIS FILE IS AUTOGENERATED! ANY MANUAL MODIFICATIONS WILL BE LOST!
//

using System;
using Tp.Integration.Common;

namespace Tp.Integration.Messages.EntityLifecycle.Messages
{
	[Serializable]
	public class BuildCreatedMessage : EntityCreatedMessage<BuildDTO>, ISagaMessage
	{
	}

	[Serializable]
	public class BuildDeletedMessage : EntityDeletedMessage<BuildDTO>, ISagaMessage
	{
	}

	[Serializable]
	public class BuildUpdatedMessage : EntityUpdatedMessage<BuildDTO, BuildField>, ISagaMessage
	{
		
	}

}
