// 
// THIS FILE IS AUTOGENERATED! ANY MANUAL MODIFICATIONS WILL BE LOST!
//

using System;
using Tp.Integration.Common;

namespace Tp.Integration.Messages.EntityLifecycle.Messages
{
	[Serializable]
	public class CustomActivityCreatedMessage : EntityCreatedMessage<CustomActivityDTO>, ISagaMessage
	{
	}

	[Serializable]
	public class CustomActivityDeletedMessage : EntityDeletedMessage<CustomActivityDTO>, ISagaMessage
	{
	}

	[Serializable]
	public class CustomActivityUpdatedMessage : EntityUpdatedMessage<CustomActivityDTO, CustomActivityField>, ISagaMessage
	{
		
	}

}
