// 
// THIS FILE IS AUTOGENERATED! ANY MANUAL MODIFICATIONS WILL BE LOST!
//

using System;
using Tp.Integration.Common;

namespace Tp.Integration.Messages.EntityLifecycle.Messages
{
	[Serializable]
	public class EpicCreatedMessage : EntityCreatedMessage<EpicDTO>, ISagaMessage
	{
	}

	[Serializable]
	public class EpicDeletedMessage : EntityDeletedMessage<EpicDTO>, ISagaMessage
	{
	}

	[Serializable]
	public class EpicUpdatedMessage : EntityUpdatedMessage<EpicDTO, EpicField>, ISagaMessage
	{
		
	}

}
