// 
// THIS FILE IS AUTOGENERATED! ANY MANUAL MODIFICATIONS WILL BE LOST!
//

using System;
using Tp.Integration.Common;

namespace Tp.Integration.Messages.EntityLifecycle.Messages
{
	[Serializable]
	public class ExternalReferenceCreatedMessage : EntityCreatedMessage<ExternalReferenceDTO>, ISagaMessage
	{
	}

	[Serializable]
	public class ExternalReferenceDeletedMessage : EntityDeletedMessage<ExternalReferenceDTO>, ISagaMessage
	{
	}

	[Serializable]
	public class ExternalReferenceUpdatedMessage : EntityUpdatedMessage<ExternalReferenceDTO, ExternalReferenceField>, ISagaMessage
	{
		
	}

}
