// 
// THIS FILE IS AUTOGENERATED! ANY MANUAL MODIFICATIONS WILL BE LOST!
//

using System;
using Tp.Integration.Common;

namespace Tp.Integration.Messages.EntityLifecycle.Messages
{
	[Serializable]
	public class GeneralListItemCreatedMessage : EntityCreatedMessage<GeneralListItemDTO>, ISagaMessage
	{
	}

	[Serializable]
	public class GeneralListItemDeletedMessage : EntityDeletedMessage<GeneralListItemDTO>, ISagaMessage
	{
	}

	[Serializable]
	public class GeneralListItemUpdatedMessage : EntityUpdatedMessage<GeneralListItemDTO, GeneralListItemField>, ISagaMessage
	{
		
	}

}
