// 
// THIS FILE IS AUTOGENERATED! ANY MANUAL MODIFICATIONS WILL BE LOST!
//

using System;
using Tp.Integration.Common;

namespace Tp.Integration.Messages.EntityLifecycle.Messages
{
	[Serializable]
	public class GeneralFieldExtensionCreatedMessage : EntityCreatedMessage<GeneralFieldExtensionDTO>, ISagaMessage
	{
	}

	[Serializable]
	public class GeneralFieldExtensionDeletedMessage : EntityDeletedMessage<GeneralFieldExtensionDTO>, ISagaMessage
	{
	}

	[Serializable]
	public class GeneralFieldExtensionUpdatedMessage : EntityUpdatedMessage<GeneralFieldExtensionDTO, GeneralFieldExtensionField>, ISagaMessage
	{
		
	}

}
