// 
// THIS FILE IS AUTOGENERATED! ANY MANUAL MODIFICATIONS WILL BE LOST!
//

using System;
using Tp.Integration.Common;

namespace Tp.Integration.Messages.EntityLifecycle.Messages
{
	[Serializable]
	public class GeneralRelationTypeCreatedMessage : EntityCreatedMessage<GeneralRelationTypeDTO>, ISagaMessage
	{
	}

	[Serializable]
	public class GeneralRelationTypeDeletedMessage : EntityDeletedMessage<GeneralRelationTypeDTO>, ISagaMessage
	{
	}

	[Serializable]
	public class GeneralRelationTypeUpdatedMessage : EntityUpdatedMessage<GeneralRelationTypeDTO, GeneralRelationTypeField>, ISagaMessage
	{
		
	}

}
