// 
// THIS FILE IS AUTOGENERATED! ANY MANUAL MODIFICATIONS WILL BE LOST!
//

using System;
using Tp.Integration.Common;

namespace Tp.Integration.Messages.EntityLifecycle.Messages
{
	[Serializable]
	public class GlobalSettingCreatedMessage : EntityCreatedMessage<GlobalSettingDTO>, ISagaMessage
	{
	}

	[Serializable]
	public class GlobalSettingDeletedMessage : EntityDeletedMessage<GlobalSettingDTO>, ISagaMessage
	{
	}

	[Serializable]
	public class GlobalSettingUpdatedMessage : EntityUpdatedMessage<GlobalSettingDTO, GlobalSettingField>, ISagaMessage
	{
		
	}

}
