// 
// THIS FILE IS AUTOGENERATED! ANY MANUAL MODIFICATIONS WILL BE LOST!
//

using System;
using Tp.Integration.Common;

namespace Tp.Integration.Messages.EntityLifecycle.Messages
{
	[Serializable]
	public class MessageCreatedMessage : EntityCreatedMessage<MessageDTO>, ISagaMessage
	{
	}

	[Serializable]
	public class MessageDeletedMessage : EntityDeletedMessage<MessageDTO>, ISagaMessage
	{
	}

	[Serializable]
	public class MessageUpdatedMessage : EntityUpdatedMessage<MessageDTO, MessageField>, ISagaMessage
	{
		
	}

}
