// 
// THIS FILE IS AUTOGENERATED! ANY MANUAL MODIFICATIONS WILL BE LOST!
//

using System;
using Tp.Integration.Common;

namespace Tp.Integration.Messages.EntityLifecycle.Messages
{
	[Serializable]
	public class PluginProfileCreatedMessage : EntityCreatedMessage<PluginProfileDTO>, ISagaMessage
	{
	}

	[Serializable]
	public class PluginProfileDeletedMessage : EntityDeletedMessage<PluginProfileDTO>, ISagaMessage
	{
	}

	[Serializable]
	public class PluginProfileUpdatedMessage : EntityUpdatedMessage<PluginProfileDTO, PluginProfileField>, ISagaMessage
	{
		
	}

}
