// 
// THIS FILE IS AUTOGENERATED! ANY MANUAL MODIFICATIONS WILL BE LOST!
//

using System;
using Tp.Integration.Common;

namespace Tp.Integration.Messages.EntityLifecycle.Messages
{
	[Serializable]
	public class ProgramCreatedMessage : EntityCreatedMessage<ProgramDTO>, ISagaMessage
	{
	}

	[Serializable]
	public class ProgramDeletedMessage : EntityDeletedMessage<ProgramDTO>, ISagaMessage
	{
	}

	[Serializable]
	public class ProgramUpdatedMessage : EntityUpdatedMessage<ProgramDTO, ProgramField>, ISagaMessage
	{
		
	}

}
