// 
// THIS FILE IS AUTOGENERATED! ANY MANUAL MODIFICATIONS WILL BE LOST!
//

using System;
using Tp.Integration.Common;

namespace Tp.Integration.Messages.EntityLifecycle.Messages
{
	[Serializable]
	public class RequestRequesterCreatedMessage : EntityCreatedMessage<RequestRequesterDTO>, ISagaMessage
	{
	}

	[Serializable]
	public class RequestRequesterDeletedMessage : EntityDeletedMessage<RequestRequesterDTO>, ISagaMessage
	{
	}

	[Serializable]
	public class RequestRequesterUpdatedMessage : EntityUpdatedMessage<RequestRequesterDTO, RequestRequesterField>, ISagaMessage
	{
		
	}

}
