// 
// THIS FILE IS AUTOGENERATED! ANY MANUAL MODIFICATIONS WILL BE LOST!
//

using System;
using Tp.Integration.Common;

namespace Tp.Integration.Messages.EntityLifecycle.Messages
{
	[Serializable]
	public class RequestTypeCreatedMessage : EntityCreatedMessage<RequestTypeDTO>, ISagaMessage
	{
	}

	[Serializable]
	public class RequestTypeDeletedMessage : EntityDeletedMessage<RequestTypeDTO>, ISagaMessage
	{
	}

	[Serializable]
	public class RequestTypeUpdatedMessage : EntityUpdatedMessage<RequestTypeDTO, RequestTypeField>, ISagaMessage
	{
		
	}

}
