// 
// THIS FILE IS AUTOGENERATED! ANY MANUAL MODIFICATIONS WILL BE LOST!
//

using System;
using Tp.Integration.Common;

namespace Tp.Integration.Messages.EntityLifecycle.Messages
{
	[Serializable]
	public class RequesterCreatedMessage : EntityCreatedMessage<RequesterDTO>, ISagaMessage
	{
	}

	[Serializable]
	public class RequesterDeletedMessage : EntityDeletedMessage<RequesterDTO>, ISagaMessage
	{
	}

	[Serializable]
	public class RequesterUpdatedMessage : EntityUpdatedMessage<RequesterDTO, RequesterField>, ISagaMessage
	{
		
	}

}
