// 
// THIS FILE IS AUTOGENERATED! ANY MANUAL MODIFICATIONS WILL BE LOST!
//

using System;
using Tp.Integration.Common;

namespace Tp.Integration.Messages.EntityLifecycle.Messages
{
	[Serializable]
	public class RevisionAssignableCreatedMessage : EntityCreatedMessage<RevisionAssignableDTO>, ISagaMessage
	{
	}

	[Serializable]
	public class RevisionAssignableDeletedMessage : EntityDeletedMessage<RevisionAssignableDTO>, ISagaMessage
	{
	}

	[Serializable]
	public class RevisionAssignableUpdatedMessage : EntityUpdatedMessage<RevisionAssignableDTO, RevisionAssignableField>, ISagaMessage
	{
		
	}

}
