// 
// THIS FILE IS AUTOGENERATED! ANY MANUAL MODIFICATIONS WILL BE LOST!
//

using System;
using Tp.Integration.Common;

namespace Tp.Integration.Messages.EntityLifecycle.Messages
{
	[Serializable]
	public class RoleEffortCreatedMessage : EntityCreatedMessage<RoleEffortDTO>, ISagaMessage
	{
	}

	[Serializable]
	public class RoleEffortDeletedMessage : EntityDeletedMessage<RoleEffortDTO>, ISagaMessage
	{
	}

	[Serializable]
	public class RoleEffortUpdatedMessage : EntityUpdatedMessage<RoleEffortDTO, RoleEffortField>, ISagaMessage
	{
		
	}

}
