// 
// THIS FILE IS AUTOGENERATED! ANY MANUAL MODIFICATIONS WILL BE LOST!
//

using System;
using Tp.Integration.Common;

namespace Tp.Integration.Messages.EntityLifecycle.Messages
{
	[Serializable]
	public class SquadCreatedMessage : EntityCreatedMessage<SquadDTO>, ISagaMessage
	{
	}

	[Serializable]
	public class SquadDeletedMessage : EntityDeletedMessage<SquadDTO>, ISagaMessage
	{
	}

	[Serializable]
	public class SquadUpdatedMessage : EntityUpdatedMessage<SquadDTO, SquadField>, ISagaMessage
	{
		
	}

}
