// 
// THIS FILE IS AUTOGENERATED! ANY MANUAL MODIFICATIONS WILL BE LOST!
//

using System;
using Tp.Integration.Common;

namespace Tp.Integration.Messages.EntityLifecycle.Messages
{
	[Serializable]
	public class SystemUserCreatedMessage : EntityCreatedMessage<SystemUserDTO>, ISagaMessage
	{
	}

	[Serializable]
	public class SystemUserDeletedMessage : EntityDeletedMessage<SystemUserDTO>, ISagaMessage
	{
	}

	[Serializable]
	public class SystemUserUpdatedMessage : EntityUpdatedMessage<SystemUserDTO, SystemUserField>, ISagaMessage
	{
		
	}

}
