// 
// THIS FILE IS AUTOGENERATED! ANY MANUAL MODIFICATIONS WILL BE LOST!
//

using System;
using Tp.Integration.Common;

namespace Tp.Integration.Messages.EntityLifecycle.Messages
{
	[Serializable]
	public class TagBundleTagCreatedMessage : EntityCreatedMessage<TagBundleTagDTO>, ISagaMessage
	{
	}

	[Serializable]
	public class TagBundleTagDeletedMessage : EntityDeletedMessage<TagBundleTagDTO>, ISagaMessage
	{
	}

	[Serializable]
	public class TagBundleTagUpdatedMessage : EntityUpdatedMessage<TagBundleTagDTO, TagBundleTagField>, ISagaMessage
	{
		
	}

}
