// 
// THIS FILE IS AUTOGENERATED! ANY MANUAL MODIFICATIONS WILL BE LOST!
//

using System;
using Tp.Integration.Common;

namespace Tp.Integration.Messages.EntityLifecycle.Messages
{
	[Serializable]
	public class TeamCreatedMessage : EntityCreatedMessage<TeamDTO>, ISagaMessage
	{
	}

	[Serializable]
	public class TeamDeletedMessage : EntityDeletedMessage<TeamDTO>, ISagaMessage
	{
	}

	[Serializable]
	public class TeamUpdatedMessage : EntityUpdatedMessage<TeamDTO, TeamField>, ISagaMessage
	{
		
	}

}
