// 
// THIS FILE IS AUTOGENERATED! ANY MANUAL MODIFICATIONS WILL BE LOST!
//

using System;
using Tp.Integration.Common;

namespace Tp.Integration.Messages.EntityLifecycle.Messages
{
	[Serializable]
	public class TeamListItemCreatedMessage : EntityCreatedMessage<TeamListItemDTO>, ISagaMessage
	{
	}

	[Serializable]
	public class TeamListItemDeletedMessage : EntityDeletedMessage<TeamListItemDTO>, ISagaMessage
	{
	}

	[Serializable]
	public class TeamListItemUpdatedMessage : EntityUpdatedMessage<TeamListItemDTO, TeamListItemField>, ISagaMessage
	{
		
	}

}
