// 
// THIS FILE IS AUTOGENERATED! ANY MANUAL MODIFICATIONS WILL BE LOST!
//

using System;
using Tp.Integration.Common;

namespace Tp.Integration.Messages.EntityLifecycle.Messages
{
	[Serializable]
	public class TermCreatedMessage : EntityCreatedMessage<TermDTO>, ISagaMessage
	{
	}

	[Serializable]
	public class TermDeletedMessage : EntityDeletedMessage<TermDTO>, ISagaMessage
	{
	}

	[Serializable]
	public class TermUpdatedMessage : EntityUpdatedMessage<TermDTO, TermField>, ISagaMessage
	{
		
	}

}
