// 
// THIS FILE IS AUTOGENERATED! ANY MANUAL MODIFICATIONS WILL BE LOST!
//

using System;
using Tp.Integration.Common;

namespace Tp.Integration.Messages.EntityLifecycle.Messages
{
	[Serializable]
	public class TestCaseCreatedMessage : EntityCreatedMessage<TestCaseDTO>, ISagaMessage
	{
	}

	[Serializable]
	public class TestCaseDeletedMessage : EntityDeletedMessage<TestCaseDTO>, ISagaMessage
	{
	}

	[Serializable]
	public class TestCaseUpdatedMessage : EntityUpdatedMessage<TestCaseDTO, TestCaseField>, ISagaMessage
	{
		
	}

}
