// 
// THIS FILE IS AUTOGENERATED! ANY MANUAL MODIFICATIONS WILL BE LOST!
//

using System;
using Tp.Integration.Common;

namespace Tp.Integration.Messages.EntityLifecycle.Messages
{
	[Serializable]
	public class TestCaseRunBugCreatedMessage : EntityCreatedMessage<TestCaseRunBugDTO>, ISagaMessage
	{
	}

	[Serializable]
	public class TestCaseRunBugDeletedMessage : EntityDeletedMessage<TestCaseRunBugDTO>, ISagaMessage
	{
	}

	[Serializable]
	public class TestCaseRunBugUpdatedMessage : EntityUpdatedMessage<TestCaseRunBugDTO, TestCaseRunBugField>, ISagaMessage
	{
		
	}

}
