// 
// THIS FILE IS AUTOGENERATED! ANY MANUAL MODIFICATIONS WILL BE LOST!
//

using System;
using Tp.Integration.Common;

namespace Tp.Integration.Messages.EntityLifecycle.Messages
{
	[Serializable]
	public class TimeCreatedMessage : EntityCreatedMessage<TimeDTO>, ISagaMessage
	{
	}

	[Serializable]
	public class TimeDeletedMessage : EntityDeletedMessage<TimeDTO>, ISagaMessage
	{
	}

	[Serializable]
	public class TimeUpdatedMessage : EntityUpdatedMessage<TimeDTO, TimeField>, ISagaMessage
	{
		
	}

}
