// 
// THIS FILE IS AUTOGENERATED! ANY MANUAL MODIFICATIONS WILL BE LOST!
//

using System;
using Tp.Integration.Common;

namespace Tp.Integration.Messages.EntityLifecycle.Messages
{
	[Serializable]
	public class TpProfileCreatedMessage : EntityCreatedMessage<TpProfileDTO>, ISagaMessage
	{
	}

	[Serializable]
	public class TpProfileDeletedMessage : EntityDeletedMessage<TpProfileDTO>, ISagaMessage
	{
	}

	[Serializable]
	public class TpProfileUpdatedMessage : EntityUpdatedMessage<TpProfileDTO, TpProfileField>, ISagaMessage
	{
		
	}

}
