// 
// THIS FILE IS AUTOGENERATED! ANY MANUAL MODIFICATIONS WILL BE LOST!
//

using System;
using Tp.Integration.Common;

namespace Tp.Integration.Messages.EntityLifecycle.Messages
{
	[Serializable]
	public class TpSessionCreatedMessage : EntityCreatedMessage<TpSessionDTO>, ISagaMessage
	{
	}

	[Serializable]
	public class TpSessionDeletedMessage : EntityDeletedMessage<TpSessionDTO>, ISagaMessage
	{
	}

	[Serializable]
	public class TpSessionUpdatedMessage : EntityUpdatedMessage<TpSessionDTO, TpSessionField>, ISagaMessage
	{
		
	}

}
