// 
// THIS FILE IS AUTOGENERATED! ANY MANUAL MODIFICATIONS WILL BE LOST!
//

using System;
using Tp.Integration.Common;

namespace Tp.Integration.Messages.EntityLifecycle.Messages
{
	[Serializable]
	public class UserProjectAllocationCreatedMessage : EntityCreatedMessage<UserProjectAllocationDTO>, ISagaMessage
	{
	}

	[Serializable]
	public class UserProjectAllocationDeletedMessage : EntityDeletedMessage<UserProjectAllocationDTO>, ISagaMessage
	{
	}

	[Serializable]
	public class UserProjectAllocationUpdatedMessage : EntityUpdatedMessage<UserProjectAllocationDTO, UserProjectAllocationField>, ISagaMessage
	{
		
	}

}
