// 
// THIS FILE IS AUTOGENERATED! ANY MANUAL MODIFICATIONS WILL BE LOST!
//

using System;
using Tp.Integration.Common;

namespace Tp.Integration.Messages.EntityLifecycle.Messages
{
	[Serializable]
	public class WorkflowCreatedMessage : EntityCreatedMessage<WorkflowDTO>, ISagaMessage
	{
	}

	[Serializable]
	public class WorkflowDeletedMessage : EntityDeletedMessage<WorkflowDTO>, ISagaMessage
	{
	}

	[Serializable]
	public class WorkflowUpdatedMessage : EntityUpdatedMessage<WorkflowDTO, WorkflowField>, ISagaMessage
	{
		
	}

}
