//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tp.TestRunImport.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tp.TestRunImport.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to token=undefined&amp;selenium.version=1.0-beta-2&amp;selenium.revision=2330&amp;result=failed&amp;totalTime=66&amp;numTestPasses=4&amp;numTestFailures=1&amp;numCommandPasses=5&amp;numCommandFailures=1&amp;numCommandErrors=1&amp;testTable.1=%3Cdiv%3E%0D%0A%3Ctable+border%3D%221%22+cellpadding%3D%221%22+cellspacing%3D%221%22%3E%0D%0A%3Cthead%3E%0D%0A%3Ctr+class%3D%22title+status_passed%22%3E%3Ctd+rowspan%3D%221%22+colspan%3D%223%22%3EBuildUp%3C%2Ftd%3E%3C%2Ftr%3E%0D%0A%3C%2Fthead%3E%3Ctbody%3E%0D%0A%3Ctr+class%3D%22++status_done%22+style%3D%22cursor [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SimpleSeleniumTestResult {
            get {
                return ResourceManager.GetString("SimpleSeleniumTestResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;no&quot;?&gt;
        ///&lt;!--This file represents the results of running a test suite--&gt;
        ///&lt;test-results name=&quot;D:\trunk\Code\Main\Tp.UnitTests\bin\Tp.UnitTests.exe&quot; total=&quot;3&quot; errors=&quot;0&quot; failures=&quot;0&quot; not-run=&quot;0&quot; inconclusive=&quot;0&quot; ignored=&quot;0&quot; skipped=&quot;0&quot; invalid=&quot;0&quot; date=&quot;2011-06-13&quot; time=&quot;15:45:02&quot;&gt;
        ///  &lt;environment nunit-version=&quot;2.5.9.10348&quot; clr-version=&quot;2.0.50727.5444&quot; os-version=&quot;Microsoft Windows NT 6.1.7601 Service Pack 1&quot; platform=&quot;Win32NT&quot; cwd=&quot;D:\trunk\Code\Libs\NUnit&quot; machi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SimpleTestCaseTestResult {
            get {
                return ResourceManager.GetString("SimpleTestCaseTestResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to token=undefined&amp;selenium.version=1.0-beta-2&amp;selenium.revision=2330&amp;result=failed&amp;totalTime=66&amp;numTestPasses=4&amp;numTestFailures=1&amp;numCommandPasses=5&amp;numCommandFailures=1&amp;numCommandErrors=1&amp;testTable.1=%3Cdiv%3E%0D%0A%3Ctable+border%3D%221%22+cellpadding%3D%221%22+cellspacing%3D%221%22%3E%0D%0A%3Cthead%3E%0D%0A%3Ctr+class%3D%22title+status_passed%22%3E%3Ctd+rowspan%3D%221%22+colspan%3D%223%22%3EBuildUp_1001%3C%2Ftd%3E%3C%2Ftr%3E%0D%0A%3C%2Fthead%3E%3Ctbody%3E%0D%0A%3Ctr+class%3D%22++status_done%22+style%3D%22c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestIdRegExpSeleniumTestResult {
            get {
                return ResourceManager.GetString("TestIdRegExpSeleniumTestResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;no&quot;?&gt;
        ///&lt;!--This file represents the results of running a test suite--&gt;
        ///&lt;test-results name=&quot;D:\trunk\Code\Main\Tp.UnitTests\bin\Tp.UnitTests.exe&quot; total=&quot;3&quot; errors=&quot;0&quot; failures=&quot;0&quot; not-run=&quot;0&quot; inconclusive=&quot;0&quot; ignored=&quot;0&quot; skipped=&quot;0&quot; invalid=&quot;0&quot; date=&quot;2011-06-13&quot; time=&quot;15:45:02&quot;&gt;
        ///  &lt;environment nunit-version=&quot;2.5.9.10348&quot; clr-version=&quot;2.0.50727.5444&quot; os-version=&quot;Microsoft Windows NT 6.1.7601 Service Pack 1&quot; platform=&quot;Win32NT&quot; cwd=&quot;D:\trunk\Code\Libs\NUnit&quot; machi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestIdRegExpTestCaseTestResult {
            get {
                return ResourceManager.GetString("TestIdRegExpTestCaseTestResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to token=undefined&amp;selenium.version=1.0-beta-2&amp;selenium.revision=2330&amp;result=failed&amp;totalTime=66&amp;numTestPasses=4&amp;numTestFailures=1&amp;numCommandPasses=5&amp;numCommandFailures=1&amp;numCommandErrors=1&amp;testTable.1=%3Cdiv%3E%0D%0A%3Ctable+border%3D%221%22+cellpadding%3D%221%22+cellspacing%3D%221%22%3E%0D%0A%3Cthead%3E%0D%0A%3Ctr+class%3D%22title+status_passed%22%3E%3Ctd+rowspan%3D%221%22+colspan%3D%223%22%3EBuildUp_Test%3C%2Ftd%3E%3C%2Ftr%3E%0D%0A%3C%2Fthead%3E%3Ctbody%3E%0D%0A%3Ctr+class%3D%22++status_done%22+style%3D%22c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestNameRegExpSeleniumTestResult {
            get {
                return ResourceManager.GetString("TestNameRegExpSeleniumTestResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;no&quot;?&gt;
        ///&lt;!--This file represents the results of running a test suite--&gt;
        ///&lt;test-results name=&quot;D:\trunk\Code\Main\Tp.UnitTests\bin\Tp.UnitTests.exe&quot; total=&quot;3&quot; errors=&quot;0&quot; failures=&quot;0&quot; not-run=&quot;0&quot; inconclusive=&quot;0&quot; ignored=&quot;0&quot; skipped=&quot;0&quot; invalid=&quot;0&quot; date=&quot;2011-06-13&quot; time=&quot;15:45:02&quot;&gt;
        ///  &lt;environment nunit-version=&quot;2.5.9.10348&quot; clr-version=&quot;2.0.50727.5444&quot; os-version=&quot;Microsoft Windows NT 6.1.7601 Service Pack 1&quot; platform=&quot;Win32NT&quot; cwd=&quot;D:\trunk\Code\Libs\NUnit&quot; machi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestNameRegExpTestCaseTestResult {
            get {
                return ResourceManager.GetString("TestNameRegExpTestCaseTestResult", resourceCulture);
            }
        }
    }
}
