// 
// THIS FILE IS AUTOGENERATED! ANY MANUAL MODIFICATIONS WILL BE LOST!
//

using System;
using Tp.Integration.Common;

namespace Tp.Integration.Messages.EntityLifecycle.Commands
{
	[Serializable]
	public class CreateCustomRuleCommand : CreateEntityCommand<CustomRuleDTO>
	{
		public CreateCustomRuleCommand(CustomRuleDTO dto) : base(dto)
		{
		}
	}

	[Serializable]
	public class UpdateCustomRuleCommand : UpdateEntityCommand<CustomRuleDTO>
	{
		public UpdateCustomRuleCommand(CustomRuleDTO dto) : base(dto)
		{
		}

		public UpdateCustomRuleCommand(CustomRuleDTO dto, Enum[] changedFields) : base(dto, changedFields)
		{
		}
	}

	[Serializable]
	public class DeleteCustomRuleCommand : DeleteEntityCommand<CustomRuleDTO>
	{
		public DeleteCustomRuleCommand(int id) : base(id)
		{
		}
	}

}
