// 
// THIS FILE IS AUTOGENERATED! ANY MANUAL MODIFICATIONS WILL BE LOST!
//

using System;
using Tp.Integration.Common;

namespace Tp.Integration.Messages.EntityLifecycle.Commands
{
	[Serializable]
	public class CreateCustomActivityCommand : CreateEntityCommand<CustomActivityDTO>
	{
		public CreateCustomActivityCommand(CustomActivityDTO dto) : base(dto)
		{
		}
	}

	[Serializable]
	public class UpdateCustomActivityCommand : UpdateEntityCommand<CustomActivityDTO>
	{
		public UpdateCustomActivityCommand(CustomActivityDTO dto) : base(dto)
		{
		}

		public UpdateCustomActivityCommand(CustomActivityDTO dto, Enum[] changedFields) : base(dto, changedFields)
		{
		}
	}

	[Serializable]
	public class DeleteCustomActivityCommand : DeleteEntityCommand<CustomActivityDTO>
	{
		public DeleteCustomActivityCommand(int id) : base(id)
		{
		}
	}

}
