// 
// THIS FILE IS AUTOGENERATED! ANY MANUAL MODIFICATIONS WILL BE LOST!
//

using System;
using Tp.Integration.Common;

namespace Tp.Integration.Messages.EntityLifecycle.Commands
{
	[Serializable]
	public class CreateGeneralNumericPriorityListItemCommand : CreateEntityCommand<GeneralNumericPriorityListItemDTO>
	{
		public CreateGeneralNumericPriorityListItemCommand(GeneralNumericPriorityListItemDTO dto) : base(dto)
		{
		}
	}

	[Serializable]
	public class UpdateGeneralNumericPriorityListItemCommand : UpdateEntityCommand<GeneralNumericPriorityListItemDTO>
	{
		public UpdateGeneralNumericPriorityListItemCommand(GeneralNumericPriorityListItemDTO dto) : base(dto)
		{
		}

		public UpdateGeneralNumericPriorityListItemCommand(GeneralNumericPriorityListItemDTO dto, Enum[] changedFields) : base(dto, changedFields)
		{
		}
	}

	[Serializable]
	public class DeleteGeneralNumericPriorityListItemCommand : DeleteEntityCommand<GeneralNumericPriorityListItemDTO>
	{
		public DeleteGeneralNumericPriorityListItemCommand(int id) : base(id)
		{
		}
	}

}
