// 
// THIS FILE IS AUTOGENERATED! ANY MANUAL MODIFICATIONS WILL BE LOST!
//

using System;
using Tp.Integration.Common;

namespace Tp.Integration.Messages.EntityLifecycle.Commands
{
	[Serializable]
	public class CreateGeneralConversionCommand : CreateEntityCommand<GeneralConversionDTO>
	{
		public CreateGeneralConversionCommand(GeneralConversionDTO dto) : base(dto)
		{
		}
	}

	[Serializable]
	public class UpdateGeneralConversionCommand : UpdateEntityCommand<GeneralConversionDTO>
	{
		public UpdateGeneralConversionCommand(GeneralConversionDTO dto) : base(dto)
		{
		}

		public UpdateGeneralConversionCommand(GeneralConversionDTO dto, Enum[] changedFields) : base(dto, changedFields)
		{
		}
	}

	[Serializable]
	public class DeleteGeneralConversionCommand : DeleteEntityCommand<GeneralConversionDTO>
	{
		public DeleteGeneralConversionCommand(int id) : base(id)
		{
		}
	}

}
