// 
// THIS FILE IS AUTOGENERATED! ANY MANUAL MODIFICATIONS WILL BE LOST!
//

using System;
using Tp.Integration.Common;

namespace Tp.Integration.Messages.EntityLifecycle.Commands
{
	[Serializable]
	public class CreateGeneralFieldExtensionCommand : CreateEntityCommand<GeneralFieldExtensionDTO>
	{
		public CreateGeneralFieldExtensionCommand(GeneralFieldExtensionDTO dto) : base(dto)
		{
		}
	}

	[Serializable]
	public class UpdateGeneralFieldExtensionCommand : UpdateEntityCommand<GeneralFieldExtensionDTO>
	{
		public UpdateGeneralFieldExtensionCommand(GeneralFieldExtensionDTO dto) : base(dto)
		{
		}

		public UpdateGeneralFieldExtensionCommand(GeneralFieldExtensionDTO dto, Enum[] changedFields) : base(dto, changedFields)
		{
		}
	}

	[Serializable]
	public class DeleteGeneralFieldExtensionCommand : DeleteEntityCommand<GeneralFieldExtensionDTO>
	{
		public DeleteGeneralFieldExtensionCommand(int id) : base(id)
		{
		}
	}

}
