// 
// THIS FILE IS AUTOGENERATED! ANY MANUAL MODIFICATIONS WILL BE LOST!
//

using System;
using Tp.Integration.Common;

namespace Tp.Integration.Messages.EntityLifecycle.Commands
{
	[Serializable]
	public class CreateGeneralRelationCommand : CreateEntityCommand<GeneralRelationDTO>
	{
		public CreateGeneralRelationCommand(GeneralRelationDTO dto) : base(dto)
		{
		}
	}

	[Serializable]
	public class UpdateGeneralRelationCommand : UpdateEntityCommand<GeneralRelationDTO>
	{
		public UpdateGeneralRelationCommand(GeneralRelationDTO dto) : base(dto)
		{
		}

		public UpdateGeneralRelationCommand(GeneralRelationDTO dto, Enum[] changedFields) : base(dto, changedFields)
		{
		}
	}

	[Serializable]
	public class DeleteGeneralRelationCommand : DeleteEntityCommand<GeneralRelationDTO>
	{
		public DeleteGeneralRelationCommand(int id) : base(id)
		{
		}
	}

}
