// 
// THIS FILE IS AUTOGENERATED! ANY MANUAL MODIFICATIONS WILL BE LOST!
//

using System;
using Tp.Integration.Common;

namespace Tp.Integration.Messages.EntityLifecycle.Commands
{
	[Serializable]
	public class CreateGlobalSettingCommand : CreateEntityCommand<GlobalSettingDTO>
	{
		public CreateGlobalSettingCommand(GlobalSettingDTO dto) : base(dto)
		{
		}
	}

	[Serializable]
	public class UpdateGlobalSettingCommand : UpdateEntityCommand<GlobalSettingDTO>
	{
		public UpdateGlobalSettingCommand(GlobalSettingDTO dto) : base(dto)
		{
		}

		public UpdateGlobalSettingCommand(GlobalSettingDTO dto, Enum[] changedFields) : base(dto, changedFields)
		{
		}
	}

	[Serializable]
	public class DeleteGlobalSettingCommand : DeleteEntityCommand<GlobalSettingDTO>
	{
		public DeleteGlobalSettingCommand(int id) : base(id)
		{
		}
	}

}
