// 
// THIS FILE IS AUTOGENERATED! ANY MANUAL MODIFICATIONS WILL BE LOST!
//

using System;
using Tp.Integration.Common;

namespace Tp.Integration.Messages.EntityLifecycle.Commands
{
	[Serializable]
	public class CreateLicenseCommand : CreateEntityCommand<LicenseDTO>
	{
		public CreateLicenseCommand(LicenseDTO dto) : base(dto)
		{
		}
	}

	[Serializable]
	public class UpdateLicenseCommand : UpdateEntityCommand<LicenseDTO>
	{
		public UpdateLicenseCommand(LicenseDTO dto) : base(dto)
		{
		}

		public UpdateLicenseCommand(LicenseDTO dto, Enum[] changedFields) : base(dto, changedFields)
		{
		}
	}

	[Serializable]
	public class DeleteLicenseCommand : DeleteEntityCommand<LicenseDTO>
	{
		public DeleteLicenseCommand(int id) : base(id)
		{
		}
	}

}
