// 
// THIS FILE IS AUTOGENERATED! ANY MANUAL MODIFICATIONS WILL BE LOST!
//

using System;
using Tp.Integration.Common;

namespace Tp.Integration.Messages.EntityLifecycle.Commands
{
	[Serializable]
	public class CreatePasswordRecoveryCommand : CreateEntityCommand<PasswordRecoveryDTO>
	{
		public CreatePasswordRecoveryCommand(PasswordRecoveryDTO dto) : base(dto)
		{
		}
	}

	[Serializable]
	public class UpdatePasswordRecoveryCommand : UpdateEntityCommand<PasswordRecoveryDTO>
	{
		public UpdatePasswordRecoveryCommand(PasswordRecoveryDTO dto) : base(dto)
		{
		}

		public UpdatePasswordRecoveryCommand(PasswordRecoveryDTO dto, Enum[] changedFields) : base(dto, changedFields)
		{
		}
	}

	[Serializable]
	public class DeletePasswordRecoveryCommand : DeleteEntityCommand<PasswordRecoveryDTO>
	{
		public DeletePasswordRecoveryCommand(int id) : base(id)
		{
		}
	}

}
