// 
// THIS FILE IS AUTOGENERATED! ANY MANUAL MODIFICATIONS WILL BE LOST!
//

using System;
using Tp.Integration.Common;

namespace Tp.Integration.Messages.EntityLifecycle.Commands
{
	[Serializable]
	public class CreatePluginProfileCommand : CreateEntityCommand<PluginProfileDTO>
	{
		public CreatePluginProfileCommand(PluginProfileDTO dto) : base(dto)
		{
		}
	}

	[Serializable]
	public class UpdatePluginProfileCommand : UpdateEntityCommand<PluginProfileDTO>
	{
		public UpdatePluginProfileCommand(PluginProfileDTO dto) : base(dto)
		{
		}

		public UpdatePluginProfileCommand(PluginProfileDTO dto, Enum[] changedFields) : base(dto, changedFields)
		{
		}
	}

	[Serializable]
	public class DeletePluginProfileCommand : DeleteEntityCommand<PluginProfileDTO>
	{
		public DeletePluginProfileCommand(int id) : base(id)
		{
		}
	}

}
