// 
// THIS FILE IS AUTOGENERATED! ANY MANUAL MODIFICATIONS WILL BE LOST!
//

using System;
using Tp.Integration.Common;

namespace Tp.Integration.Messages.EntityLifecycle.Commands
{
	[Serializable]
	public class CreateProjectCommand : CreateEntityCommand<ProjectDTO>
	{
		public CreateProjectCommand(ProjectDTO dto) : base(dto)
		{
		}
	}

	[Serializable]
	public class UpdateProjectCommand : UpdateEntityCommand<ProjectDTO>
	{
		public UpdateProjectCommand(ProjectDTO dto) : base(dto)
		{
		}

		public UpdateProjectCommand(ProjectDTO dto, Enum[] changedFields) : base(dto, changedFields)
		{
		}
	}

	[Serializable]
	public class DeleteProjectCommand : DeleteEntityCommand<ProjectDTO>
	{
		public DeleteProjectCommand(int id) : base(id)
		{
		}
	}

}
