// 
// THIS FILE IS AUTOGENERATED! ANY MANUAL MODIFICATIONS WILL BE LOST!
//

using System;
using Tp.Integration.Common;

namespace Tp.Integration.Messages.EntityLifecycle.Commands
{
	[Serializable]
	public class CreateReleaseProjectCommand : CreateEntityCommand<ReleaseProjectDTO>
	{
		public CreateReleaseProjectCommand(ReleaseProjectDTO dto) : base(dto)
		{
		}
	}

	[Serializable]
	public class UpdateReleaseProjectCommand : UpdateEntityCommand<ReleaseProjectDTO>
	{
		public UpdateReleaseProjectCommand(ReleaseProjectDTO dto) : base(dto)
		{
		}

		public UpdateReleaseProjectCommand(ReleaseProjectDTO dto, Enum[] changedFields) : base(dto, changedFields)
		{
		}
	}

	[Serializable]
	public class DeleteReleaseProjectCommand : DeleteEntityCommand<ReleaseProjectDTO>
	{
		public DeleteReleaseProjectCommand(int id) : base(id)
		{
		}
	}

}
