// 
// THIS FILE IS AUTOGENERATED! ANY MANUAL MODIFICATIONS WILL BE LOST!
//

using System;
using Tp.Integration.Common;

namespace Tp.Integration.Messages.EntityLifecycle.Commands
{
	[Serializable]
	public class CreateRuleEngineUserCommand : CreateEntityCommand<RuleEngineUserDTO>
	{
		public CreateRuleEngineUserCommand(RuleEngineUserDTO dto) : base(dto)
		{
		}
	}

	[Serializable]
	public class UpdateRuleEngineUserCommand : UpdateEntityCommand<RuleEngineUserDTO>
	{
		public UpdateRuleEngineUserCommand(RuleEngineUserDTO dto) : base(dto)
		{
		}

		public UpdateRuleEngineUserCommand(RuleEngineUserDTO dto, Enum[] changedFields) : base(dto, changedFields)
		{
		}
	}

	[Serializable]
	public class DeleteRuleEngineUserCommand : DeleteEntityCommand<RuleEngineUserDTO>
	{
		public DeleteRuleEngineUserCommand(int id) : base(id)
		{
		}
	}

}
