// 
// THIS FILE IS AUTOGENERATED! ANY MANUAL MODIFICATIONS WILL BE LOST!
//

using System;
using Tp.Integration.Common;

namespace Tp.Integration.Messages.EntityLifecycle.Commands
{
	[Serializable]
	public class CreateSquadProjectCommand : CreateEntityCommand<SquadProjectDTO>
	{
		public CreateSquadProjectCommand(SquadProjectDTO dto) : base(dto)
		{
		}
	}

	[Serializable]
	public class UpdateSquadProjectCommand : UpdateEntityCommand<SquadProjectDTO>
	{
		public UpdateSquadProjectCommand(SquadProjectDTO dto) : base(dto)
		{
		}

		public UpdateSquadProjectCommand(SquadProjectDTO dto, Enum[] changedFields) : base(dto, changedFields)
		{
		}
	}

	[Serializable]
	public class DeleteSquadProjectCommand : DeleteEntityCommand<SquadProjectDTO>
	{
		public DeleteSquadProjectCommand(int id) : base(id)
		{
		}
	}

}
