// 
// THIS FILE IS AUTOGENERATED! ANY MANUAL MODIFICATIONS WILL BE LOST!
//

using System;
using Tp.Integration.Common;

namespace Tp.Integration.Messages.EntityLifecycle.Commands
{
	[Serializable]
	public class CreateSquadCommand : CreateEntityCommand<SquadDTO>
	{
		public CreateSquadCommand(SquadDTO dto) : base(dto)
		{
		}
	}

	[Serializable]
	public class UpdateSquadCommand : UpdateEntityCommand<SquadDTO>
	{
		public UpdateSquadCommand(SquadDTO dto) : base(dto)
		{
		}

		public UpdateSquadCommand(SquadDTO dto, Enum[] changedFields) : base(dto, changedFields)
		{
		}
	}

	[Serializable]
	public class DeleteSquadCommand : DeleteEntityCommand<SquadDTO>
	{
		public DeleteSquadCommand(int id) : base(id)
		{
		}
	}

}
