// 
// THIS FILE IS AUTOGENERATED! ANY MANUAL MODIFICATIONS WILL BE LOST!
//

using System;
using Tp.Integration.Common;

namespace Tp.Integration.Messages.EntityLifecycle.Commands
{
	[Serializable]
	public class CreateSquadMemberCommand : CreateEntityCommand<SquadMemberDTO>
	{
		public CreateSquadMemberCommand(SquadMemberDTO dto) : base(dto)
		{
		}
	}

	[Serializable]
	public class UpdateSquadMemberCommand : UpdateEntityCommand<SquadMemberDTO>
	{
		public UpdateSquadMemberCommand(SquadMemberDTO dto) : base(dto)
		{
		}

		public UpdateSquadMemberCommand(SquadMemberDTO dto, Enum[] changedFields) : base(dto, changedFields)
		{
		}
	}

	[Serializable]
	public class DeleteSquadMemberCommand : DeleteEntityCommand<SquadMemberDTO>
	{
		public DeleteSquadMemberCommand(int id) : base(id)
		{
		}
	}

}
