// 
// THIS FILE IS AUTOGENERATED! ANY MANUAL MODIFICATIONS WILL BE LOST!
//

using System;
using Tp.Integration.Common;

namespace Tp.Integration.Messages.EntityLifecycle.Commands
{
	[Serializable]
	public class CreateSystemUserCommand : CreateEntityCommand<SystemUserDTO>
	{
		public CreateSystemUserCommand(SystemUserDTO dto) : base(dto)
		{
		}
	}

	[Serializable]
	public class UpdateSystemUserCommand : UpdateEntityCommand<SystemUserDTO>
	{
		public UpdateSystemUserCommand(SystemUserDTO dto) : base(dto)
		{
		}

		public UpdateSystemUserCommand(SystemUserDTO dto, Enum[] changedFields) : base(dto, changedFields)
		{
		}
	}

	[Serializable]
	public class DeleteSystemUserCommand : DeleteEntityCommand<SystemUserDTO>
	{
		public DeleteSystemUserCommand(int id) : base(id)
		{
		}
	}

}
