// 
// THIS FILE IS AUTOGENERATED! ANY MANUAL MODIFICATIONS WILL BE LOST!
//

using System;
using Tp.Integration.Common;

namespace Tp.Integration.Messages.EntityLifecycle.Commands
{
	[Serializable]
	public class CreateTagGeneralCommand : CreateEntityCommand<TagGeneralDTO>
	{
		public CreateTagGeneralCommand(TagGeneralDTO dto) : base(dto)
		{
		}
	}

	[Serializable]
	public class UpdateTagGeneralCommand : UpdateEntityCommand<TagGeneralDTO>
	{
		public UpdateTagGeneralCommand(TagGeneralDTO dto) : base(dto)
		{
		}

		public UpdateTagGeneralCommand(TagGeneralDTO dto, Enum[] changedFields) : base(dto, changedFields)
		{
		}
	}

	[Serializable]
	public class DeleteTagGeneralCommand : DeleteEntityCommand<TagGeneralDTO>
	{
		public DeleteTagGeneralCommand(int id) : base(id)
		{
		}
	}

}
