// 
// THIS FILE IS AUTOGENERATED! ANY MANUAL MODIFICATIONS WILL BE LOST!
//

using System;
using Tp.Integration.Common;

namespace Tp.Integration.Messages.EntityLifecycle.Commands
{
	[Serializable]
	public class CreateTestPlanRunBugCommand : CreateEntityCommand<TestPlanRunBugDTO>
	{
		public CreateTestPlanRunBugCommand(TestPlanRunBugDTO dto) : base(dto)
		{
		}
	}

	[Serializable]
	public class UpdateTestPlanRunBugCommand : UpdateEntityCommand<TestPlanRunBugDTO>
	{
		public UpdateTestPlanRunBugCommand(TestPlanRunBugDTO dto) : base(dto)
		{
		}

		public UpdateTestPlanRunBugCommand(TestPlanRunBugDTO dto, Enum[] changedFields) : base(dto, changedFields)
		{
		}
	}

	[Serializable]
	public class DeleteTestPlanRunBugCommand : DeleteEntityCommand<TestPlanRunBugDTO>
	{
		public DeleteTestPlanRunBugCommand(int id) : base(id)
		{
		}
	}

}
