// 
// THIS FILE IS AUTOGENERATED! ANY MANUAL MODIFICATIONS WILL BE LOST!
//

using System;
using Tp.Integration.Common;

namespace Tp.Integration.Messages.EntityLifecycle.Commands
{
	[Serializable]
	public class CreateTestPlanTestPlanCommand : CreateEntityCommand<TestPlanTestPlanDTO>
	{
		public CreateTestPlanTestPlanCommand(TestPlanTestPlanDTO dto) : base(dto)
		{
		}
	}

	[Serializable]
	public class UpdateTestPlanTestPlanCommand : UpdateEntityCommand<TestPlanTestPlanDTO>
	{
		public UpdateTestPlanTestPlanCommand(TestPlanTestPlanDTO dto) : base(dto)
		{
		}

		public UpdateTestPlanTestPlanCommand(TestPlanTestPlanDTO dto, Enum[] changedFields) : base(dto, changedFields)
		{
		}
	}

	[Serializable]
	public class DeleteTestPlanTestPlanCommand : DeleteEntityCommand<TestPlanTestPlanDTO>
	{
		public DeleteTestPlanTestPlanCommand(int id) : base(id)
		{
		}
	}

}
