// 
// THIS FILE IS AUTOGENERATED! ANY MANUAL MODIFICATIONS WILL BE LOST!
//

using System;
using Tp.Integration.Common;

namespace Tp.Integration.Messages.EntityLifecycle.Commands
{
	[Serializable]
	public class CreateTestPlanCommand : CreateEntityCommand<TestPlanDTO>
	{
		public CreateTestPlanCommand(TestPlanDTO dto) : base(dto)
		{
		}
	}

	[Serializable]
	public class UpdateTestPlanCommand : UpdateEntityCommand<TestPlanDTO>
	{
		public UpdateTestPlanCommand(TestPlanDTO dto) : base(dto)
		{
		}

		public UpdateTestPlanCommand(TestPlanDTO dto, Enum[] changedFields) : base(dto, changedFields)
		{
		}
	}

	[Serializable]
	public class DeleteTestPlanCommand : DeleteEntityCommand<TestPlanDTO>
	{
		public DeleteTestPlanCommand(int id) : base(id)
		{
		}
	}

}
