// 
// THIS FILE IS AUTOGENERATED! ANY MANUAL MODIFICATIONS WILL BE LOST!
//

using System;
using Tp.Integration.Common;

namespace Tp.Integration.Messages.EntityLifecycle.Commands
{
	[Serializable]
	public class CreateTestRunItemHierarchyLinkCommand : CreateEntityCommand<TestRunItemHierarchyLinkDTO>
	{
		public CreateTestRunItemHierarchyLinkCommand(TestRunItemHierarchyLinkDTO dto) : base(dto)
		{
		}
	}

	[Serializable]
	public class UpdateTestRunItemHierarchyLinkCommand : UpdateEntityCommand<TestRunItemHierarchyLinkDTO>
	{
		public UpdateTestRunItemHierarchyLinkCommand(TestRunItemHierarchyLinkDTO dto) : base(dto)
		{
		}

		public UpdateTestRunItemHierarchyLinkCommand(TestRunItemHierarchyLinkDTO dto, Enum[] changedFields) : base(dto, changedFields)
		{
		}
	}

	[Serializable]
	public class DeleteTestRunItemHierarchyLinkCommand : DeleteEntityCommand<TestRunItemHierarchyLinkDTO>
	{
		public DeleteTestRunItemHierarchyLinkCommand(int id) : base(id)
		{
		}
	}

}
