// 
// THIS FILE IS AUTOGENERATED! ANY MANUAL MODIFICATIONS WILL BE LOST!
//

using System;
using Tp.Integration.Common;

namespace Tp.Integration.Messages.EntityLifecycle.Commands
{
	[Serializable]
	public class CreateTestStepCommand : CreateEntityCommand<TestStepDTO>
	{
		public CreateTestStepCommand(TestStepDTO dto) : base(dto)
		{
		}
	}

	[Serializable]
	public class UpdateTestStepCommand : UpdateEntityCommand<TestStepDTO>
	{
		public UpdateTestStepCommand(TestStepDTO dto) : base(dto)
		{
		}

		public UpdateTestStepCommand(TestStepDTO dto, Enum[] changedFields) : base(dto, changedFields)
		{
		}
	}

	[Serializable]
	public class DeleteTestStepCommand : DeleteEntityCommand<TestStepDTO>
	{
		public DeleteTestStepCommand(int id) : base(id)
		{
		}
	}

}
