// 
// THIS FILE IS AUTOGENERATED! ANY MANUAL MODIFICATIONS WILL BE LOST!
//

using System;
using Tp.Integration.Common;

namespace Tp.Integration.Messages.EntityLifecycle.Commands
{
	[Serializable]
	public class CreateTpSessionCommand : CreateEntityCommand<TpSessionDTO>
	{
		public CreateTpSessionCommand(TpSessionDTO dto) : base(dto)
		{
		}
	}

	[Serializable]
	public class UpdateTpSessionCommand : UpdateEntityCommand<TpSessionDTO>
	{
		public UpdateTpSessionCommand(TpSessionDTO dto) : base(dto)
		{
		}

		public UpdateTpSessionCommand(TpSessionDTO dto, Enum[] changedFields) : base(dto, changedFields)
		{
		}
	}

	[Serializable]
	public class DeleteTpSessionCommand : DeleteEntityCommand<TpSessionDTO>
	{
		public DeleteTpSessionCommand(int id) : base(id)
		{
		}
	}

}
