// 
// THIS FILE IS AUTOGENERATED! ANY MANUAL MODIFICATIONS WILL BE LOST!
//

using System;
using Tp.Integration.Common;

namespace Tp.Integration.Messages.EntityLifecycle.Commands
{
	[Serializable]
	public class CreateWorkflowCommand : CreateEntityCommand<WorkflowDTO>
	{
		public CreateWorkflowCommand(WorkflowDTO dto) : base(dto)
		{
		}
	}

	[Serializable]
	public class UpdateWorkflowCommand : UpdateEntityCommand<WorkflowDTO>
	{
		public UpdateWorkflowCommand(WorkflowDTO dto) : base(dto)
		{
		}

		public UpdateWorkflowCommand(WorkflowDTO dto, Enum[] changedFields) : base(dto, changedFields)
		{
		}
	}

	[Serializable]
	public class DeleteWorkflowCommand : DeleteEntityCommand<WorkflowDTO>
	{
		public DeleteWorkflowCommand(int id) : base(id)
		{
		}
	}

}
